/**
 * This code was generated by Builder.io.
 */
import * as React from "react";

interface MyComponentProps {
  text: string;
}

function MyComponent({ text }: MyComponentProps) {
  return (
    <h1 className="pr-5 w-full max-md:mx-auto max-md:text-4xl max-md:leading-10 max-md:text-center max-sm:mx-auto max-sm:w-4/5">
      {text}
    </h1>
  );
}

export default function App() {
  return (
    <main>
      <MyComponent text="Your essential tool for success" />
      <div className="mt-5 min-h-[400px]">
        <script
          charSet="utf-8"
          type="text/javascript"
          src="//js.hsforms.net/forms/embed/v2.js"
        ></script>
        <script
          dangerouslySetInnerHTML={{
            __html: `hbspt.forms.create({
              region: "na1",
              portalId: "8544885",
              formId: "0fc3ae12-5d97-4685-9bf0-6fa8ada0ddf4"
            });`,
          }}
        />
      </div>
    </main>
  );
}