/**
 * This code was generated by Builder.io.
 */
import * as React from "react";

function MyComponent() {
  return (
    <>
      <div className="flex flex-col justify-center bg-white">
        <div className="flex flex-col w-full max-md:max-w-full">
          <div className="flex overflow-hidden relative flex-col justify-center pt-2.5 pb-20 w-full mix-blend-darken min-h-[832px] max-md:max-w-full">
            <img
              loading="lazy"
              srcSet="https://cdn.builder.io/api/v1/image/assets/TEMP/bb6f8e92aceebe4b027a5d04793f84f6635decc1cd4e274e655f5d800929bedf?apiKey=3c43d1e5501c48e2896654e6368e313f&width=100 100w, https://cdn.builder.io/api/v1/image/assets/TEMP/bb6f8e92aceebe4b027a5d04793f84f6635decc1cd4e274e655f5d800929bedf?apiKey=3c43d1e5501c48e2896654e6368e313f&width=200 200w, https://cdn.builder.io/api/v1/image/assets/TEMP/bb6f8e92aceebe4b027a5d04793f84f6635decc1cd4e274e655f5d800929bedf?apiKey=3c43d1e5501c48e2896654e6368e313f&width=400 400w, https://cdn.builder.io/api/v1/image/assets/TEMP/bb6f8e92aceebe4b027a5d04793f84f6635decc1cd4e274e655f5d800929bedf?apiKey=3c43d1e5501c48e2896654e6368e313f&width=800 800w, https://cdn.builder.io/api/v1/image/assets/TEMP/bb6f8e92aceebe4b027a5d04793f84f6635decc1cd4e274e655f5d800929bedf?apiKey=3c43d1e5501c48e2896654e6368e313f&width=1200 1200w, https://cdn.builder.io/api/v1/image/assets/TEMP/bb6f8e92aceebe4b027a5d04793f84f6635decc1cd4e274e655f5d800929bedf?apiKey=3c43d1e5501c48e2896654e6368e313f&width=1600 1600w, https://cdn.builder.io/api/v1/image/assets/TEMP/bb6f8e92aceebe4b027a5d04793f84f6635decc1cd4e274e655f5d800929bedf?apiKey=3c43d1e5501c48e2896654e6368e313f&width=2000 2000w, https://cdn.builder.io/api/v1/image/assets/TEMP/bb6f8e92aceebe4b027a5d04793f84f6635decc1cd4e274e655f5d800929bedf?apiKey=3c43d1e5501c48e2896654e6368e313f&"
              className="object-cover absolute inset-0 size-full"
            />
            <div className="flex relative flex-row gap-5 justify-between px-16 py-2 mb-auto w-full max-md:px-5 max-md:max-w-full">
              <img
                loading="lazy"
                src="https://cdn.builder.io/api/v1/image/assets/TEMP/a6f0226e7096b413711dfc55417603b99fdce9b0afb17ed90cdff827c740482f?apiKey=3c43d1e5501c48e2896654e6368e313f&"
                className="shrink-0 max-w-full aspect-[3.23] w-[180px]"
              />
              <div className="flex gap-5 justify-between my-auto">
                <div className="flex flex-col justify-center px-px text-xl font-bold text-white">
                  <div className="justify-center px-9 py-3 bg-blue-600 max-md:px-5">
                    Book a Demo
                  </div>
                </div>
                <div
                  className="flex flex-col justify-center py-1.5 my-auto w-[35px]"
                >
                  <div className="shrink-0 h-1 bg-white max-sm:bg-black" />
                  <div className="shrink-0 mt-2 h-1 bg-white max-sm:bg-black" />
                  <div className="shrink-0 mt-2 h-1 bg-white max-sm:bg-black" />
                </div>
              </div>
            </div>
            <div className="flex relative flex-col justify-center items-start self-center pl-16 mt-6 mb-2.5 max-w-full font-bold w-[142%] max-md:pr-5 max-sm:pl-5">
              <div className="flex flex-col justify-end pt-20 max-w-full">
                <div className="flex flex-col justify-center mt-64 text-5xl leading-[60px] text-stone-900 max-md:pr-5 max-md:mt-10 max-md:max-w-full max-md:text-4xl max-md:leading-[53px]">
                  <div className="w-6/12 max-md:mr-0.5 max-md:max-w-full max-md:text-4xl max-md:leading-[53px] max-sm:w-full">
                    <span className="bg-yellow-400">
                      Build Dreams with Precision
                    </span>
                  </div>
                  <div className="mt-4 w-6/12 text-lg leading-7 text-stone-50 max-md:max-w-full max-sm:w-full">
                    Craft custom builds with laying the foundation for custom
                    homes that bring dream designs to reality
                  </div>
                  <div className="flex flex-col justify-center mt-4 mr-auto w-auto max-w-full text-xl text-white">
                    <div className="justify-center px-10 py-3 border-2 border-solid bg-stone-900 border-stone-900 max-md:px-5">
                      Get Started
                    </div>
                  </div>
                </div>
              </div>
            </div>
          </div>
          <div className="flex justify-center items-center p-10 w-full text-base leading-6 text-center text-black max-md:px-5 max-md:max-w-full">
            <div className="flex gap-5 max-md:flex-wrap max-sm:flex max-sm:flex-row max-sm:mx-auto max-sm:w-full">
              <div className="justify-center px-2.5 py-1.5 whitespace-nowrap max-sm:mx-auto">
                Estimation
              </div>
              <div className="justify-center px-2.5 py-1.5 max-sm:mx-auto">
                Client Dashboard
              </div>
              <div className="justify-center px-2.5 py-1.5 whitespace-nowrap max-sm:mx-auto">
                AutoCost
              </div>
              <div className="justify-center px-2.5 py-1.5 whitespace-nowrap max-sm:mx-auto">
                Scheduling
              </div>
              <div className="justify-center px-2.5 py-1.5 max-sm:mx-auto">
                Invoicing & Payments
              </div>
            </div>
          </div>
          <div className="flex flex-col justify-center px-16 py-20 w-full bg-stone-200 max-md:px-5 max-md:max-w-full max-sm:pt-8">
            <div className="flex flex-col justify-center p-10 mx-auto mb-2.5 bg-white rounded-xl border-2 border-solid shadow-sm border-stone-900 border-opacity-20 max-w-[1350px] max-md:px-5 max-md:mr-2.5 max-md:max-w-full max-sm:pb-10">
              <div className="flex flex-col max-md:max-w-full">
                <div className="flex justify-center items-center px-16 text-4xl font-bold leading-10 text-center text-black max-md:px-5 max-md:max-w-full">
                  <div className="justify-center px-4 py-2 bg-yellow-400 max-md:max-w-full max-sm:text-4xl max-sm:text-black max-sm:bg-white">
                    <span className="bg-yellow-400 bg-opacity-0">
                      Precision Estimating for Custom Builds
                    </span>
                  </div>
                </div>
                <div className="mt-8 text-lg leading-7 text-center text-black max-md:max-w-full">
                  Revolutionize how you handle sales with our cutting-edge
                  estimating software.
                </div>
                <div className="flex justify-center items-center px-16 py-11 mt-8 rounded-xl bg-stone-50 max-md:px-5 max-md:max-w-full">
                  <img
                    loading="lazy"
                    srcSet="https://cdn.builder.io/api/v1/image/assets/TEMP/0bfffdfd8860fcb85b504461b6ede978128ce997facc569bc563b433d6c3d614?apiKey=3c43d1e5501c48e2896654e6368e313f&width=100 100w, https://cdn.builder.io/api/v1/image/assets/TEMP/0bfffdfd8860fcb85b504461b6ede978128ce997facc569bc563b433d6c3d614?apiKey=3c43d1e5501c48e2896654e6368e313f&width=200 200w, https://cdn.builder.io/api/v1/image/assets/TEMP/0bfffdfd8860fcb85b504461b6ede978128ce997facc569bc563b433d6c3d614?apiKey=3c43d1e5501c48e2896654e6368e313f&width=400 400w, https://cdn.builder.io/api/v1/image/assets/TEMP/0bfffdfd8860fcb85b504461b6ede978128ce997facc569bc563b433d6c3d614?apiKey=3c43d1e5501c48e2896654e6368e313f&width=800 800w, https://cdn.builder.io/api/v1/image/assets/TEMP/0bfffdfd8860fcb85b504461b6ede978128ce997facc569bc563b433d6c3d614?apiKey=3c43d1e5501c48e2896654e6368e313f&width=1200 1200w, https://cdn.builder.io/api/v1/image/assets/TEMP/0bfffdfd8860fcb85b504461b6ede978128ce997facc569bc563b433d6c3d614?apiKey=3c43d1e5501c48e2896654e6368e313f&width=1600 1600w, https://cdn.builder.io/api/v1/image/assets/TEMP/0bfffdfd8860fcb85b504461b6ede978128ce997facc569bc563b433d6c3d614?apiKey=3c43d1e5501c48e2896654e6368e313f&width=2000 2000w, https://cdn.builder.io/api/v1/image/assets/TEMP/0bfffdfd8860fcb85b504461b6ede978128ce997facc569bc563b433d6c3d614?apiKey=3c43d1e5501c48e2896654e6368e313f&"
                    className="max-w-full aspect-[1.79] w-[816px]"
                  />
                </div>
                <div className="mt-8 text-lg leading-7 text-black max-md:max-w-full">
                  Our estimating tool goes beyond standard practices to level up
                  the homeowner experience and  support your sales from start to
                  finish. It demystifies pricing for homeowners, illustrating
                  how each choice affects the overall cost, thereby fostering
                  trust and understanding.
                </div>
                <div className="flex flex-col justify-center mt-8 max-w-full text-xl font-bold text-stone-900 w-[197px] max-sm:mx-auto">
                  <div className="justify-center px-11 py-3 bg-yellow-400 max-md:px-5 max-sm:text-center">
                    Learn More
                  </div>
                </div>
                <div className="px-px mt-8 mr-8 max-md:mr-2.5 max-md:max-w-full">
                  <div className="flex gap-5 max-md:flex-col max-md:gap-0">
                    <div className="flex flex-col w-[33%] max-md:ml-0 max-md:w-full">
                      <div className="flex flex-col grow self-stretch max-md:mt-8">
                        <div className="flex justify-center items-center px-14 py-9 rounded-xl bg-stone-200 max-md:px-5">
                          <img
                            loading="lazy"
                            src="https://cdn.builder.io/api/v1/image/assets/TEMP/283c0be0f573ce928fb875441272e569bd6e03497bb99bf2e5b042ae832d9d51?apiKey=3c43d1e5501c48e2896654e6368e313f&"
                            className="aspect-[1.16] w-[191px]"
                          />
                        </div>
                        <div className="mt-5 text-2xl font-bold leading-8 text-black">
                          Uplift your sales
                        </div>
                        <div className="mt-5 text-lg leading-7 text-black">
                          Supporting the sales cycle by turning confusion into
                          confidence. Elevate the presentation of the estimates
                          to build confidence and trust. Educate the homeowner.
                          the estimate allows them to show what’s include and
                          show how the homeowner choices - like upgrading -
                          impact the total cost
                        </div>
                      </div>
                    </div>
                    <div className="flex flex-col ml-5 w-[33%] max-md:ml-0 max-md:w-full">
                      <div className="flex flex-col grow self-stretch pb-14 max-md:mt-8 max-sm:mb-8">
                        <div className="flex flex-col justify-center px-9 py-11 rounded-xl bg-stone-200 max-md:px-5">
                          <div className="flex overflow-hidden relative flex-col items-center px-5 pt-1 pb-4 aspect-[1.64] max-md:px-5">
                            <img
                              loading="lazy"
                              srcSet="https://cdn.builder.io/api/v1/image/assets/TEMP/57a903e76bbeeb66370fbf0b0bd4960a450d96e63373e7bee2526aa362bfea10?apiKey=3c43d1e5501c48e2896654e6368e313f&width=100 100w, https://cdn.builder.io/api/v1/image/assets/TEMP/57a903e76bbeeb66370fbf0b0bd4960a450d96e63373e7bee2526aa362bfea10?apiKey=3c43d1e5501c48e2896654e6368e313f&width=200 200w, https://cdn.builder.io/api/v1/image/assets/TEMP/57a903e76bbeeb66370fbf0b0bd4960a450d96e63373e7bee2526aa362bfea10?apiKey=3c43d1e5501c48e2896654e6368e313f&width=400 400w, https://cdn.builder.io/api/v1/image/assets/TEMP/57a903e76bbeeb66370fbf0b0bd4960a450d96e63373e7bee2526aa362bfea10?apiKey=3c43d1e5501c48e2896654e6368e313f&width=800 800w, https://cdn.builder.io/api/v1/image/assets/TEMP/57a903e76bbeeb66370fbf0b0bd4960a450d96e63373e7bee2526aa362bfea10?apiKey=3c43d1e5501c48e2896654e6368e313f&width=1200 1200w, https://cdn.builder.io/api/v1/image/assets/TEMP/57a903e76bbeeb66370fbf0b0bd4960a450d96e63373e7bee2526aa362bfea10?apiKey=3c43d1e5501c48e2896654e6368e313f&width=1600 1600w, https://cdn.builder.io/api/v1/image/assets/TEMP/57a903e76bbeeb66370fbf0b0bd4960a450d96e63373e7bee2526aa362bfea10?apiKey=3c43d1e5501c48e2896654e6368e313f&width=2000 2000w, https://cdn.builder.io/api/v1/image/assets/TEMP/57a903e76bbeeb66370fbf0b0bd4960a450d96e63373e7bee2526aa362bfea10?apiKey=3c43d1e5501c48e2896654e6368e313f&"
                              className="object-cover absolute inset-0 size-full"
                            />
                            <img
                              loading="lazy"
                              srcSet="https://cdn.builder.io/api/v1/image/assets/TEMP/271c5f63c7e1b3597dec41f4c047ea406f97f689dfa4ba4c11c598dfc079d2a4?apiKey=3c43d1e5501c48e2896654e6368e313f&width=100 100w, https://cdn.builder.io/api/v1/image/assets/TEMP/271c5f63c7e1b3597dec41f4c047ea406f97f689dfa4ba4c11c598dfc079d2a4?apiKey=3c43d1e5501c48e2896654e6368e313f&width=200 200w, https://cdn.builder.io/api/v1/image/assets/TEMP/271c5f63c7e1b3597dec41f4c047ea406f97f689dfa4ba4c11c598dfc079d2a4?apiKey=3c43d1e5501c48e2896654e6368e313f&width=400 400w, https://cdn.builder.io/api/v1/image/assets/TEMP/271c5f63c7e1b3597dec41f4c047ea406f97f689dfa4ba4c11c598dfc079d2a4?apiKey=3c43d1e5501c48e2896654e6368e313f&width=800 800w, https://cdn.builder.io/api/v1/image/assets/TEMP/271c5f63c7e1b3597dec41f4c047ea406f97f689dfa4ba4c11c598dfc079d2a4?apiKey=3c43d1e5501c48e2896654e6368e313f&width=1200 1200w, https://cdn.builder.io/api/v1/image/assets/TEMP/271c5f63c7e1b3597dec41f4c047ea406f97f689dfa4ba4c11c598dfc079d2a4?apiKey=3c43d1e5501c48e2896654e6368e313f&width=1600 1600w, https://cdn.builder.io/api/v1/image/assets/TEMP/271c5f63c7e1b3597dec41f4c047ea406f97f689dfa4ba4c11c598dfc079d2a4?apiKey=3c43d1e5501c48e2896654e6368e313f&width=2000 2000w, https://cdn.builder.io/api/v1/image/assets/TEMP/271c5f63c7e1b3597dec41f4c047ea406f97f689dfa4ba4c11c598dfc079d2a4?apiKey=3c43d1e5501c48e2896654e6368e313f&"
                              className="aspect-[1.54] w-[196px]"
                            />
                          </div>
                        </div>
                        <div className="mt-5 text-2xl font-bold leading-8 text-black">
                          Save time
                        </div>
                        <div className="mt-5 text-lg leading-7 text-black">
                          Reduce estimating time from hours to minutes for the
                          actual estimate - never start from scratch on
                          estimates again.
                          <br />
                          All your variations at your fingertips - create
                          lightening fast quoting that’s customized to each job.
                        </div>
                      </div>
                    </div>
                    <div className="flex flex-col ml-5 w-[33%] max-md:ml-0 max-md:w-full">
                      <img
                        loading="lazy"
                        srcSet="https://cdn.builder.io/api/v1/image/assets/TEMP/2d3afe5d0df88ca4557554e4d689cb447218f7667f02f6cf8e1a3883f02d4971?apiKey=3c43d1e5501c48e2896654e6368e313f&width=100 100w, https://cdn.builder.io/api/v1/image/assets/TEMP/2d3afe5d0df88ca4557554e4d689cb447218f7667f02f6cf8e1a3883f02d4971?apiKey=3c43d1e5501c48e2896654e6368e313f&width=200 200w, https://cdn.builder.io/api/v1/image/assets/TEMP/2d3afe5d0df88ca4557554e4d689cb447218f7667f02f6cf8e1a3883f02d4971?apiKey=3c43d1e5501c48e2896654e6368e313f&width=400 400w, https://cdn.builder.io/api/v1/image/assets/TEMP/2d3afe5d0df88ca4557554e4d689cb447218f7667f02f6cf8e1a3883f02d4971?apiKey=3c43d1e5501c48e2896654e6368e313f&width=800 800w, https://cdn.builder.io/api/v1/image/assets/TEMP/2d3afe5d0df88ca4557554e4d689cb447218f7667f02f6cf8e1a3883f02d4971?apiKey=3c43d1e5501c48e2896654e6368e313f&width=1200 1200w, https://cdn.builder.io/api/v1/image/assets/TEMP/2d3afe5d0df88ca4557554e4d689cb447218f7667f02f6cf8e1a3883f02d4971?apiKey=3c43d1e5501c48e2896654e6368e313f&width=1600 1600w, https://cdn.builder.io/api/v1/image/assets/TEMP/2d3afe5d0df88ca4557554e4d689cb447218f7667f02f6cf8e1a3883f02d4971?apiKey=3c43d1e5501c48e2896654e6368e313f&width=2000 2000w, https://cdn.builder.io/api/v1/image/assets/TEMP/2d3afe5d0df88ca4557554e4d689cb447218f7667f02f6cf8e1a3883f02d4971?apiKey=3c43d1e5501c48e2896654e6368e313f&"
                        className="w-full aspect-[0.98] max-md:hidden max-sm:flex"
                      />
                      <img
                        loading="lazy"
                        srcSet="https://cdn.builder.io/api/v1/image/assets/TEMP/50caff25b97b8d2189aff7b1076fb93caeae33be5d278c1c1961b14737061959?apiKey=3c43d1e5501c48e2896654e6368e313f&width=100 100w, https://cdn.builder.io/api/v1/image/assets/TEMP/50caff25b97b8d2189aff7b1076fb93caeae33be5d278c1c1961b14737061959?apiKey=3c43d1e5501c48e2896654e6368e313f&width=200 200w, https://cdn.builder.io/api/v1/image/assets/TEMP/50caff25b97b8d2189aff7b1076fb93caeae33be5d278c1c1961b14737061959?apiKey=3c43d1e5501c48e2896654e6368e313f&width=400 400w, https://cdn.builder.io/api/v1/image/assets/TEMP/50caff25b97b8d2189aff7b1076fb93caeae33be5d278c1c1961b14737061959?apiKey=3c43d1e5501c48e2896654e6368e313f&width=800 800w, https://cdn.builder.io/api/v1/image/assets/TEMP/50caff25b97b8d2189aff7b1076fb93caeae33be5d278c1c1961b14737061959?apiKey=3c43d1e5501c48e2896654e6368e313f&width=1200 1200w, https://cdn.builder.io/api/v1/image/assets/TEMP/50caff25b97b8d2189aff7b1076fb93caeae33be5d278c1c1961b14737061959?apiKey=3c43d1e5501c48e2896654e6368e313f&width=1600 1600w, https://cdn.builder.io/api/v1/image/assets/TEMP/50caff25b97b8d2189aff7b1076fb93caeae33be5d278c1c1961b14737061959?apiKey=3c43d1e5501c48e2896654e6368e313f&width=2000 2000w, https://cdn.builder.io/api/v1/image/assets/TEMP/50caff25b97b8d2189aff7b1076fb93caeae33be5d278c1c1961b14737061959?apiKey=3c43d1e5501c48e2896654e6368e313f&"
                        className="w-full aspect-[0.56] max-md:flex max-sm:hidden"
                      />
                    </div>
                  </div>
                </div>
              </div>
            </div>
          </div>
          <div className="flex flex-col justify-center w-full bg-yellow-400 max-md:max-w-full">
            <div className="mx-auto w-full max-w-[1350px] max-md:max-w-full">
              <div className="flex gap-5 max-md:flex-col max-md:gap-0">
                <div className="flex flex-col w-6/12 max-md:ml-0 max-md:w-full">
                  <div className="flex flex-col grow justify-center self-stretch font-bold text-black max-md:max-w-full">
                    <div className="flex flex-col justify-center py-20 pl-16 bg-yellow-400 max-md:px-5 max-md:max-w-full max-sm:py-5">
                      <div className="flex flex-col mx-7 mt-64 mb-32 max-md:mx-2.5 max-md:my-10">
                        <div className="text-5xl leading-[60px] max-md:text-4xl max-md:leading-[53px]">
                          Time your <br />
                          follow up
                        </div>
                        <div className="mt-6 text-lg leading-7">
                          Focus your efforts where they count with our CRM
                          dashboard with real-time updates on customer
                          interactions with proposals
                        </div>
                        <div className="flex flex-col justify-center mt-6 max-w-full text-xl text-white w-[196px]">
                          <div className="justify-center px-11 py-3 bg-stone-900 max-md:px-5">
                            Learn More
                          </div>
                        </div>
                      </div>
                    </div>
                  </div>
                </div>
                <div className="flex flex-col ml-5 w-6/12 max-md:ml-0 max-md:w-full">
                  <div className="flex flex-col grow justify-center self-stretch text-lg leading-7 text-black max-md:max-w-full">
                    <div className="flex flex-col justify-center py-16 pr-16 bg-yellow-400 max-md:px-5 max-md:max-w-full max-sm:pt-5">
                      <div className="flex flex-col p-10 bg-white rounded-xl border-2 border-solid shadow-sm border-stone-900 border-opacity-20 max-md:px-5 max-md:max-w-full max-sm:py-8">
                        <img
                          loading="lazy"
                          srcSet="https://cdn.builder.io/api/v1/image/assets/TEMP/701e0115c2c26d073694a197494ff567a01b91c2df682dd88fe2d1da6a16d664?apiKey=3c43d1e5501c48e2896654e6368e313f&width=100 100w, https://cdn.builder.io/api/v1/image/assets/TEMP/701e0115c2c26d073694a197494ff567a01b91c2df682dd88fe2d1da6a16d664?apiKey=3c43d1e5501c48e2896654e6368e313f&width=200 200w, https://cdn.builder.io/api/v1/image/assets/TEMP/701e0115c2c26d073694a197494ff567a01b91c2df682dd88fe2d1da6a16d664?apiKey=3c43d1e5501c48e2896654e6368e313f&width=400 400w, https://cdn.builder.io/api/v1/image/assets/TEMP/701e0115c2c26d073694a197494ff567a01b91c2df682dd88fe2d1da6a16d664?apiKey=3c43d1e5501c48e2896654e6368e313f&width=800 800w, https://cdn.builder.io/api/v1/image/assets/TEMP/701e0115c2c26d073694a197494ff567a01b91c2df682dd88fe2d1da6a16d664?apiKey=3c43d1e5501c48e2896654e6368e313f&width=1200 1200w, https://cdn.builder.io/api/v1/image/assets/TEMP/701e0115c2c26d073694a197494ff567a01b91c2df682dd88fe2d1da6a16d664?apiKey=3c43d1e5501c48e2896654e6368e313f&width=1600 1600w, https://cdn.builder.io/api/v1/image/assets/TEMP/701e0115c2c26d073694a197494ff567a01b91c2df682dd88fe2d1da6a16d664?apiKey=3c43d1e5501c48e2896654e6368e313f&width=2000 2000w, https://cdn.builder.io/api/v1/image/assets/TEMP/701e0115c2c26d073694a197494ff567a01b91c2df682dd88fe2d1da6a16d664?apiKey=3c43d1e5501c48e2896654e6368e313f&"
                          className="w-full aspect-[1.01] max-md:max-w-full"
                        />
                        <div className="mt-8 max-md:max-w-full">
                          {" "}
                          track proposal views and interactions, ensuring you
                          follow up at the most opportune moments. Add break
                          here to emphasize two value props This overview of all
                          jobs aids in forecasting and managing your project
                          pipeline efficiently, freeing up more time for what
                          you do best: building exceptional custom homes.
                          <br />
                        </div>
                      </div>
                    </div>
                  </div>
                </div>
              </div>
            </div>
          </div>
          <div className="flex flex-col justify-center px-16 py-20 w-full bg-stone-50 max-md:px-5 max-md:max-w-full max-sm:py-8">
            <div className="flex flex-col p-10 mx-auto mb-2.5 w-full bg-white rounded-xl border-2 border-solid shadow-sm border-stone-900 border-opacity-20 max-w-[1350px] max-md:px-5 max-md:mr-2.5 max-md:max-w-full max-sm:flex max-sm:flex-col max-sm:pt-8">
              <div className="px-px max-md:max-w-full">
                <div className="flex gap-5 max-md:flex-col max-md:gap-0">
                  <div className="flex flex-col w-3/5 max-md:ml-0 max-md:w-full">
                    <div className="flex flex-col font-bold text-black max-md:mt-8 max-md:max-w-full max-sm:order-1">
                      <div className="justify-center text-4xl leading-10 whitespace-nowrap max-md:max-w-full">
                        AutoCost
                      </div>
                      <div className="justify-center mt-8 text-lg leading-7 max-md:max-w-full">
                        Our estimating tool goes beyond standard practices to
                        level up the homeowner experience and  support your
                        sales from start to finish. It demystifies pricing for
                        homeowners, illustrating how each choice affects the
                        overall cost, thereby fostering trust and understanding.
                      </div>
                      <div className="justify-center self-start px-11 py-3 mt-8 text-xl bg-yellow-400 text-stone-900 max-md:px-5">
                        Learn More
                      </div>
                    </div>
                  </div>
                  <div className="flex flex-col ml-5 w-2/5 max-md:ml-0 max-md:w-full">
                    <img
                      loading="lazy"
                      srcSet="https://cdn.builder.io/api/v1/image/assets/TEMP/e967c6cde1db28f4963c0e8cb2ec76079cb990198ac8def773a379155b1b2b1e?apiKey=3c43d1e5501c48e2896654e6368e313f&width=100 100w, https://cdn.builder.io/api/v1/image/assets/TEMP/e967c6cde1db28f4963c0e8cb2ec76079cb990198ac8def773a379155b1b2b1e?apiKey=3c43d1e5501c48e2896654e6368e313f&width=200 200w, https://cdn.builder.io/api/v1/image/assets/TEMP/e967c6cde1db28f4963c0e8cb2ec76079cb990198ac8def773a379155b1b2b1e?apiKey=3c43d1e5501c48e2896654e6368e313f&width=400 400w, https://cdn.builder.io/api/v1/image/assets/TEMP/e967c6cde1db28f4963c0e8cb2ec76079cb990198ac8def773a379155b1b2b1e?apiKey=3c43d1e5501c48e2896654e6368e313f&width=800 800w, https://cdn.builder.io/api/v1/image/assets/TEMP/e967c6cde1db28f4963c0e8cb2ec76079cb990198ac8def773a379155b1b2b1e?apiKey=3c43d1e5501c48e2896654e6368e313f&width=1200 1200w, https://cdn.builder.io/api/v1/image/assets/TEMP/e967c6cde1db28f4963c0e8cb2ec76079cb990198ac8def773a379155b1b2b1e?apiKey=3c43d1e5501c48e2896654e6368e313f&width=1600 1600w, https://cdn.builder.io/api/v1/image/assets/TEMP/e967c6cde1db28f4963c0e8cb2ec76079cb990198ac8def773a379155b1b2b1e?apiKey=3c43d1e5501c48e2896654e6368e313f&width=2000 2000w, https://cdn.builder.io/api/v1/image/assets/TEMP/e967c6cde1db28f4963c0e8cb2ec76079cb990198ac8def773a379155b1b2b1e?apiKey=3c43d1e5501c48e2896654e6368e313f&"
                      className="grow w-full aspect-[1.1] max-md:mt-8"
                    />
                  </div>
                </div>
              </div>
              <div className="flex justify-center items-center self-stretch px-16 py-20 mt-8 rounded-xl bg-stone-50 max-md:px-5 max-sm:order-2 max-sm:py-8">
                <img
                  loading="lazy"
                  srcSet="https://cdn.builder.io/api/v1/image/assets/TEMP/ab22abd4996a7804e559836d037ba0c525da0284301acdcf4cf036fafa9768a8?apiKey=3c43d1e5501c48e2896654e6368e313f&width=100 100w, https://cdn.builder.io/api/v1/image/assets/TEMP/ab22abd4996a7804e559836d037ba0c525da0284301acdcf4cf036fafa9768a8?apiKey=3c43d1e5501c48e2896654e6368e313f&width=200 200w, https://cdn.builder.io/api/v1/image/assets/TEMP/ab22abd4996a7804e559836d037ba0c525da0284301acdcf4cf036fafa9768a8?apiKey=3c43d1e5501c48e2896654e6368e313f&width=400 400w, https://cdn.builder.io/api/v1/image/assets/TEMP/ab22abd4996a7804e559836d037ba0c525da0284301acdcf4cf036fafa9768a8?apiKey=3c43d1e5501c48e2896654e6368e313f&width=800 800w, https://cdn.builder.io/api/v1/image/assets/TEMP/ab22abd4996a7804e559836d037ba0c525da0284301acdcf4cf036fafa9768a8?apiKey=3c43d1e5501c48e2896654e6368e313f&width=1200 1200w, https://cdn.builder.io/api/v1/image/assets/TEMP/ab22abd4996a7804e559836d037ba0c525da0284301acdcf4cf036fafa9768a8?apiKey=3c43d1e5501c48e2896654e6368e313f&width=1600 1600w, https://cdn.builder.io/api/v1/image/assets/TEMP/ab22abd4996a7804e559836d037ba0c525da0284301acdcf4cf036fafa9768a8?apiKey=3c43d1e5501c48e2896654e6368e313f&width=2000 2000w, https://cdn.builder.io/api/v1/image/assets/TEMP/ab22abd4996a7804e559836d037ba0c525da0284301acdcf4cf036fafa9768a8?apiKey=3c43d1e5501c48e2896654e6368e313f&"
                  className="w-full max-w-full aspect-[1.64]"
                />
              </div>
            </div>
          </div>
          <div className="flex overflow-hidden relative flex-col p-20 w-full min-h-[1299px] max-md:px-5 max-md:max-w-full">
            <img
              loading="lazy"
              srcSet="https://cdn.builder.io/api/v1/image/assets/TEMP/390f5f5ea40ec86f0b76792b191de7cfea64f72777df70d84a2339c89335a304?apiKey=3c43d1e5501c48e2896654e6368e313f&width=100 100w, https://cdn.builder.io/api/v1/image/assets/TEMP/390f5f5ea40ec86f0b76792b191de7cfea64f72777df70d84a2339c89335a304?apiKey=3c43d1e5501c48e2896654e6368e313f&width=200 200w, https://cdn.builder.io/api/v1/image/assets/TEMP/390f5f5ea40ec86f0b76792b191de7cfea64f72777df70d84a2339c89335a304?apiKey=3c43d1e5501c48e2896654e6368e313f&width=400 400w, https://cdn.builder.io/api/v1/image/assets/TEMP/390f5f5ea40ec86f0b76792b191de7cfea64f72777df70d84a2339c89335a304?apiKey=3c43d1e5501c48e2896654e6368e313f&width=800 800w, https://cdn.builder.io/api/v1/image/assets/TEMP/390f5f5ea40ec86f0b76792b191de7cfea64f72777df70d84a2339c89335a304?apiKey=3c43d1e5501c48e2896654e6368e313f&width=1200 1200w, https://cdn.builder.io/api/v1/image/assets/TEMP/390f5f5ea40ec86f0b76792b191de7cfea64f72777df70d84a2339c89335a304?apiKey=3c43d1e5501c48e2896654e6368e313f&width=1600 1600w, https://cdn.builder.io/api/v1/image/assets/TEMP/390f5f5ea40ec86f0b76792b191de7cfea64f72777df70d84a2339c89335a304?apiKey=3c43d1e5501c48e2896654e6368e313f&width=2000 2000w, https://cdn.builder.io/api/v1/image/assets/TEMP/390f5f5ea40ec86f0b76792b191de7cfea64f72777df70d84a2339c89335a304?apiKey=3c43d1e5501c48e2896654e6368e313f&"
              className="object-cover absolute inset-0 size-full"
            />
            <div className="flex relative flex-col justify-center items-start mx-auto mt-56 w-full max-w-[1350px] max-md:pr-5 max-md:mt-10 max-md:max-w-full">
              <div className="flex flex-col justify-center max-w-full w-[668px]">
                <div className="flex flex-col justify-center max-md:max-w-full">
                  <div className="flex flex-col max-md:max-w-full">
                    <div className="flex flex-col justify-center text-4xl font-bold leading-10 text-stone-900 max-md:max-w-full">
                      <div className="justify-center max-md:max-w-full">
                        <span className="bg-yellow-400">
                          Automated Scheduling to Keep Projects on Track
                        </span>
                      </div>
                    </div>
                    <div className="justify-center mt-4 max-w-full text-lg leading-7 text-white w-[345px]">
                      Transform estimates into actionable schedules in an
                      instant.{" "}
                    </div>
                  </div>
                </div>
              </div>
              <div className="relative justify-center self-start px-11 py-3 mt-7 text-xl font-bold bg-yellow-400 text-stone-900 max-md:px-5 max-md:ml-2">
                Learn More
              </div>
            </div>
            <div className="relative p-10 mx-auto mt-7 mb-2.5 w-full bg-white rounded-xl border-2 border-solid shadow-sm border-stone-900 border-opacity-20 max-w-[1350px] max-md:px-5 max-md:max-w-full max-sm:pt-6">
              <div className="flex gap-5 max-md:flex-col max-md:gap-0">
                <div className="flex flex-col w-2/5 max-md:ml-0 max-md:w-full">
                  <img
                    loading="lazy"
                    srcSet="https://cdn.builder.io/api/v1/image/assets/TEMP/0354d82ab898b3a0834c07cc75338c1682c4c269e2e244c96f931f747c0b2ed6?apiKey=3c43d1e5501c48e2896654e6368e313f&width=100 100w, https://cdn.builder.io/api/v1/image/assets/TEMP/0354d82ab898b3a0834c07cc75338c1682c4c269e2e244c96f931f747c0b2ed6?apiKey=3c43d1e5501c48e2896654e6368e313f&width=200 200w, https://cdn.builder.io/api/v1/image/assets/TEMP/0354d82ab898b3a0834c07cc75338c1682c4c269e2e244c96f931f747c0b2ed6?apiKey=3c43d1e5501c48e2896654e6368e313f&width=400 400w, https://cdn.builder.io/api/v1/image/assets/TEMP/0354d82ab898b3a0834c07cc75338c1682c4c269e2e244c96f931f747c0b2ed6?apiKey=3c43d1e5501c48e2896654e6368e313f&width=800 800w, https://cdn.builder.io/api/v1/image/assets/TEMP/0354d82ab898b3a0834c07cc75338c1682c4c269e2e244c96f931f747c0b2ed6?apiKey=3c43d1e5501c48e2896654e6368e313f&width=1200 1200w, https://cdn.builder.io/api/v1/image/assets/TEMP/0354d82ab898b3a0834c07cc75338c1682c4c269e2e244c96f931f747c0b2ed6?apiKey=3c43d1e5501c48e2896654e6368e313f&width=1600 1600w, https://cdn.builder.io/api/v1/image/assets/TEMP/0354d82ab898b3a0834c07cc75338c1682c4c269e2e244c96f931f747c0b2ed6?apiKey=3c43d1e5501c48e2896654e6368e313f&width=2000 2000w, https://cdn.builder.io/api/v1/image/assets/TEMP/0354d82ab898b3a0834c07cc75338c1682c4c269e2e244c96f931f747c0b2ed6?apiKey=3c43d1e5501c48e2896654e6368e313f&"
                    className="grow self-stretch w-full aspect-[0.72] max-md:mt-10"
                  />
                </div>
                <div className="flex flex-col ml-5 w-3/5 max-md:ml-0 max-md:w-full">
                  <div className="flex relative flex-row grow justify-center max-md:mt-10 max-md:max-w-full">
                    <div className="flex flex-col max-md:max-w-full">
                      <div className="flex justify-center items-center px-16 py-10 rounded-xl bg-stone-200 max-md:px-5 max-md:max-w-full">
                        <img
                          loading="lazy"
                          src="https://cdn.builder.io/api/v1/image/assets/TEMP/79af4a44082fa6ea1f4b228813a3ae4b15c1e902f0446dde76e32419cfd6549c?apiKey=3c43d1e5501c48e2896654e6368e313f&"
                          className="w-80 max-w-full aspect-[0.97]"
                        />
                      </div>
                      <div className="mt-6 text-xl font-bold leading-7 text-stone-900 max-md:max-w-full">
                        Reduction in sequencing errors
                      </div>
                      <div className="mt-6 text-base leading-6 text-stone-900 max-md:max-w-full">
                        Designed with custom home builders in mind, it helps
                        manage complex timelines and avoid sequencing errors,
                        crucial for keeping projects within budget and on
                        schedule. The familiar Gantt chart visualization aids in
                        planning and tracking, while instant notifications to
                        subcontractors ensure everyone is aligned with changes
                        as they happen.
                        <br />
                      </div>
                    </div>
                  </div>
                </div>
              </div>
            </div>
          </div>
          <div className="flex flex-col justify-center px-16 py-20 w-full bg-stone-50 max-md:px-5 max-md:max-w-full max-sm:pt-10">
            <div className="flex flex-col mx-auto my-2.5 w-full max-w-[1350px] max-md:px-5 max-md:mr-2.5 max-md:max-w-full">
              <div className="flex flex-col justify-center self-center max-w-full text-center text-black w-[770px]">
                <div className="flex flex-col max-md:max-w-full">
                  <div className="justify-center items-center self-center px-16 py-3.5 max-w-full text-4xl font-bold leading-10 w-[580px] max-md:px-5 max-md:max-w-full max-sm:text-4xl">
                    <span className="bg-yellow-400">
                      Efficient Payment and Invoicing Process
                    </span>
                  </div>
                  <div className="mt-6 text-base leading-6 max-md:max-w-full">
                    Enhance your financial workflow with our fast and convenient
                    invoicing and payment system.
                  </div>
                </div>
              </div>
              <div className="flex flex-col justify-center mt-8 max-md:max-w-full">
                <div className="max-md:max-w-full">
                  <div className="flex gap-5 max-md:flex-col max-md:gap-0">
                    <div className="flex flex-col w-[64%] max-md:ml-0 max-md:w-full">
                      <div className="flex flex-col grow self-stretch p-10 w-full bg-white rounded-xl border-2 border-solid shadow-sm border-stone-900 border-opacity-20 max-md:px-5 max-md:mt-8 max-md:max-w-full">
                        <div className="flex flex-col justify-center max-md:max-w-full">
                          <div className="flex flex-col justify-center px-10 py-14 rounded-xl bg-stone-200 max-md:px-5 max-md:max-w-full max-sm:py-10">
                            <img
                              loading="lazy"
                              srcSet="https://cdn.builder.io/api/v1/image/assets/TEMP/ab22abd4996a7804e559836d037ba0c525da0284301acdcf4cf036fafa9768a8?apiKey=3c43d1e5501c48e2896654e6368e313f&width=100 100w, https://cdn.builder.io/api/v1/image/assets/TEMP/ab22abd4996a7804e559836d037ba0c525da0284301acdcf4cf036fafa9768a8?apiKey=3c43d1e5501c48e2896654e6368e313f&width=200 200w, https://cdn.builder.io/api/v1/image/assets/TEMP/ab22abd4996a7804e559836d037ba0c525da0284301acdcf4cf036fafa9768a8?apiKey=3c43d1e5501c48e2896654e6368e313f&width=400 400w, https://cdn.builder.io/api/v1/image/assets/TEMP/ab22abd4996a7804e559836d037ba0c525da0284301acdcf4cf036fafa9768a8?apiKey=3c43d1e5501c48e2896654e6368e313f&width=800 800w, https://cdn.builder.io/api/v1/image/assets/TEMP/ab22abd4996a7804e559836d037ba0c525da0284301acdcf4cf036fafa9768a8?apiKey=3c43d1e5501c48e2896654e6368e313f&width=1200 1200w, https://cdn.builder.io/api/v1/image/assets/TEMP/ab22abd4996a7804e559836d037ba0c525da0284301acdcf4cf036fafa9768a8?apiKey=3c43d1e5501c48e2896654e6368e313f&width=1600 1600w, https://cdn.builder.io/api/v1/image/assets/TEMP/ab22abd4996a7804e559836d037ba0c525da0284301acdcf4cf036fafa9768a8?apiKey=3c43d1e5501c48e2896654e6368e313f&width=2000 2000w, https://cdn.builder.io/api/v1/image/assets/TEMP/ab22abd4996a7804e559836d037ba0c525da0284301acdcf4cf036fafa9768a8?apiKey=3c43d1e5501c48e2896654e6368e313f&"
                              className="w-full max-w-full aspect-[1.64]"
                            />
                          </div>
                        </div>
                        <div className="mt-8 text-base leading-6 text-black max-md:max-w-full">
                          Issue itemized invoices based on the approved estimate
                          and receive payments online, eliminating the need to
                          physically collect checks. Benefit from capped fees
                          and faster settlement options, ensuring quick access
                          to your funds without the usual banking delays. Our
                          system is designed to streamline your financial
                          operations, letting you focus more on creating
                          stunning homes.
                        </div>
                        <div className="flex flex-col justify-center mt-8 max-w-full text-xl font-bold text-stone-900 w-[196px]">
                          <div className="justify-center px-11 py-3 bg-yellow-400 max-md:px-5">
                            Learn More
                          </div>
                        </div>
                      </div>
                    </div>
                    <div className="flex flex-col ml-5 w-[36%] max-md:ml-0 max-md:w-full">
                      <div className="flex flex-col grow justify-center self-stretch max-md:mt-8">
                        <div className="flex flex-col">
                          <img
                            loading="lazy"
                            srcSet="https://cdn.builder.io/api/v1/image/assets/TEMP/4d8cc05be6e899244827b0a4dac74761255449f44613b88354cd94e24407fa32?apiKey=3c43d1e5501c48e2896654e6368e313f&width=100 100w, https://cdn.builder.io/api/v1/image/assets/TEMP/4d8cc05be6e899244827b0a4dac74761255449f44613b88354cd94e24407fa32?apiKey=3c43d1e5501c48e2896654e6368e313f&width=200 200w, https://cdn.builder.io/api/v1/image/assets/TEMP/4d8cc05be6e899244827b0a4dac74761255449f44613b88354cd94e24407fa32?apiKey=3c43d1e5501c48e2896654e6368e313f&width=400 400w, https://cdn.builder.io/api/v1/image/assets/TEMP/4d8cc05be6e899244827b0a4dac74761255449f44613b88354cd94e24407fa32?apiKey=3c43d1e5501c48e2896654e6368e313f&width=800 800w, https://cdn.builder.io/api/v1/image/assets/TEMP/4d8cc05be6e899244827b0a4dac74761255449f44613b88354cd94e24407fa32?apiKey=3c43d1e5501c48e2896654e6368e313f&width=1200 1200w, https://cdn.builder.io/api/v1/image/assets/TEMP/4d8cc05be6e899244827b0a4dac74761255449f44613b88354cd94e24407fa32?apiKey=3c43d1e5501c48e2896654e6368e313f&width=1600 1600w, https://cdn.builder.io/api/v1/image/assets/TEMP/4d8cc05be6e899244827b0a4dac74761255449f44613b88354cd94e24407fa32?apiKey=3c43d1e5501c48e2896654e6368e313f&width=2000 2000w, https://cdn.builder.io/api/v1/image/assets/TEMP/4d8cc05be6e899244827b0a4dac74761255449f44613b88354cd94e24407fa32?apiKey=3c43d1e5501c48e2896654e6368e313f&"
                            className="w-full rounded-xl aspect-[1.01]"
                          />
                          <img
                            loading="lazy"
                            srcSet="https://cdn.builder.io/api/v1/image/assets/TEMP/737a4bf7430397f4cd513027b410035715b043188afe438ea29b354bf80db5f9?apiKey=3c43d1e5501c48e2896654e6368e313f&width=100 100w, https://cdn.builder.io/api/v1/image/assets/TEMP/737a4bf7430397f4cd513027b410035715b043188afe438ea29b354bf80db5f9?apiKey=3c43d1e5501c48e2896654e6368e313f&width=200 200w, https://cdn.builder.io/api/v1/image/assets/TEMP/737a4bf7430397f4cd513027b410035715b043188afe438ea29b354bf80db5f9?apiKey=3c43d1e5501c48e2896654e6368e313f&width=400 400w, https://cdn.builder.io/api/v1/image/assets/TEMP/737a4bf7430397f4cd513027b410035715b043188afe438ea29b354bf80db5f9?apiKey=3c43d1e5501c48e2896654e6368e313f&width=800 800w, https://cdn.builder.io/api/v1/image/assets/TEMP/737a4bf7430397f4cd513027b410035715b043188afe438ea29b354bf80db5f9?apiKey=3c43d1e5501c48e2896654e6368e313f&width=1200 1200w, https://cdn.builder.io/api/v1/image/assets/TEMP/737a4bf7430397f4cd513027b410035715b043188afe438ea29b354bf80db5f9?apiKey=3c43d1e5501c48e2896654e6368e313f&width=1600 1600w, https://cdn.builder.io/api/v1/image/assets/TEMP/737a4bf7430397f4cd513027b410035715b043188afe438ea29b354bf80db5f9?apiKey=3c43d1e5501c48e2896654e6368e313f&width=2000 2000w, https://cdn.builder.io/api/v1/image/assets/TEMP/737a4bf7430397f4cd513027b410035715b043188afe438ea29b354bf80db5f9?apiKey=3c43d1e5501c48e2896654e6368e313f&"
                            className="mt-8 w-full rounded-xl aspect-[1.01]"
                          />
                        </div>
                      </div>
                    </div>
                  </div>
                </div>
              </div>
            </div>
          </div>
          <div className="flex flex-col justify-center w-full max-md:max-w-full">
            <div className="flex flex-col justify-center w-full bg-white max-md:pr-5 max-md:max-w-full" />
          </div>
        </div>
      </div>
      <div className="flex flex-row bg-white max-sm:flex max-sm:flex-col max-sm:bg-yellow-400">
        <div className="grow justify-center items-start px-16 py-20 w-auto text-8xl font-bold tracking-tighter bg-yellow-400 leading-[91px] text-stone-900 max-md:pt-10 max-md:pr-5 max-md:pl-6 max-md:max-w-full max-md:text-4xl max-md:leading-10 max-sm:w-4/5">
          Your essential tool for success
        </div>
        <div className="flex flex-col flex-wrap content-center p-16 my-24 mr-16 ml-0 w-auto max-w-full text-xl leading-5 bg-stone-900 text-zinc-500 max-md:px-5 max-md:mt-10 max-md:max-w-full max-sm:mx-5 max-sm:mt-5 max-sm:mb-8">
          <div className="text-5xl font-bold tracking-tighter text-white max-md:max-w-full max-md:text-4xl">
            Book a demo
          </div>
          <div className="mt-5 text-3xl tracking-tighter leading-7 text-white max-md:max-w-full">
            Let us show you how to boost efficiency and profitability on every
            project — from the foundation up.
          </div>
          <div className="flex gap-4 mt-5 tracking-tight max-md:flex-wrap max-sm:flex max-sm:flex-col">
            <div className="grow justify-center px-5 py-2.5 bg-white border border-solid border-neutral-600 w-fit max-sm:w-full">
              Full name
            </div>
            <div className="grow justify-center px-5 py-2.5 bg-white border border-solid border-neutral-600 w-fit max-sm:w-full">
              Demo date
            </div>
          </div>
          <div className="flex gap-4 mt-5 tracking-tight max-md:flex-wrap max-sm:flex max-sm:flex-col">
            <div className="grow justify-center px-5 py-2.5 bg-white border border-solid border-neutral-600 w-fit max-sm:w-full">
              Email address
            </div>
            <div className="grow justify-center px-5 py-2.5 bg-white border border-solid border-neutral-600 w-fit max-sm:w-full">
              Demo time
            </div>
          </div>
          <div className="flex gap-4 mt-5 tracking-tight max-md:flex-wrap max-sm:flex max-sm:flex-col">
            <div className="grow justify-center px-5 py-2.5 whitespace-nowrap bg-white border border-solid border-neutral-600 w-fit max-sm:w-full">
              Company
            </div>
            <div className="grow justify-center px-5 py-2.5 bg-white border border-solid border-neutral-600 w-fit max-sm:w-full">
              Any other information
            </div>
          </div>
          <div className="justify-center self-start px-14 py-5 mt-5 text-xl font-medium text-center whitespace-nowrap bg-yellow-400 text-stone-900 max-md:px-5 max-sm:w-6/12">
            Next
          </div>
        </div>
      </div>
      <div className="flex flex-col px-16 py-20 w-full bg-stone-900 max-md:px-5 max-md:max-w-full max-sm:pt-5 max-sm:pb-8">
        <div className="flex flex-col justify-center max-md:max-w-full">
          <div className="justify-between max-md:max-w-full">
            <div className="flex gap-5 max-md:flex-col max-md:gap-0">
              <div className="flex flex-col w-[61%] max-md:ml-0 max-md:w-full">
                <div className="grow self-stretch max-md:mt-10 max-md:max-w-full">
                  <div className="flex gap-5 max-md:flex-col max-md:gap-0">
                    <div className="flex flex-col w-[41%] max-md:ml-0 max-md:w-full">
                      <div className="flex flex-col grow justify-between self-stretch pr-3 text-base font-bold leading-6 text-center max-md:mt-10">
                        <img
                          loading="lazy"
                          src="https://cdn.builder.io/api/v1/image/assets/TEMP/10d16e7b0312cba51f479b22b65dcb82bb95362d2803659cefc44b8bab630bc0?apiKey=3c43d1e5501c48e2896654e6368e313f&"
                          className="self-stretch aspect-[3.23] w-[155px] max-sm:self-stretch"
                        />
                        <div className="flex flex-col justify-center mt-36 max-md:mt-10 max-sm:flex max-sm:flex-row">
                          <div className="justify-center px-2.5 py-1.5 bg-blue-600 text-stone-50 max-sm:mr-auto max-sm:w-2/5">
                            Book a demo
                          </div>
                          <div className="justify-center px-2.5 py-1.5 mt-2.5 whitespace-nowrap bg-stone-50 text-stone-900 max-md:px-5 max-sm:mr-auto max-sm:w-2/5">
                            Login
                          </div>
                        </div>
                      </div>
                    </div>
                    <div className="flex flex-col ml-5 w-[33%] max-md:ml-0 max-md:w-full">
                      <div className="flex flex-col leading-[150%] max-md:mt-10">
                        <div className="text-base font-bold text-yellow-400">
                          Resources
                        </div>
                        <div className="flex flex-col pb-9 mt-4 text-sm text-stone-50">
                          <div className="justify-center py-2">
                            Customer Success
                          </div>
                          <div className="justify-center py-2 whitespace-nowrap">
                            Blog
                          </div>
                          <div className="justify-center py-2 whitespace-nowrap">
                            University
                          </div>
                          <div className="justify-center py-2 whitespace-nowrap">
                            FAQ
                          </div>
                        </div>
                      </div>
                    </div>
                    <div className="flex flex-col ml-5 w-3/12 max-md:ml-0 max-md:w-full">
                      <div className="flex flex-col leading-[150%] max-md:mt-10">
                        <div className="text-base font-bold text-yellow-400">
                          Company
                        </div>
                        <div className="flex flex-col pb-9 mt-4 text-sm text-stone-50">
                          <div className="justify-center py-2">Our Story</div>
                          <div className="justify-center py-2 whitespace-nowrap">
                            Careers
                          </div>
                          <div className="justify-center py-2 whitespace-nowrap">
                            News
                          </div>
                          <div className="justify-center py-2">Contact Us</div>
                        </div>
                      </div>
                    </div>
                  </div>
                </div>
              </div>
              <div className="flex flex-col ml-5 w-[39%] max-md:ml-0 max-md:w-full">
                <div className="flex flex-col grow max-md:mt-10">
                  <div className="flex flex-col text-base">
                    <div className="font-bold text-yellow-400 leading-[150%]">
                      Subscribe
                    </div>
                    <div className="mt-4 leading-6 text-stone-50">
                      Stay informed with the latest news and updates.
                    </div>
                  </div>
                  <div className="flex flex-col mt-6">
                    <div className="flex flex-col text-base leading-6">
                      <div className="justify-center p-3 bg-white text-stone-500">
                        Enter your email
                      </div>
                      <div className="justify-center self-start px-5 py-3 mt-2 font-bold whitespace-nowrap bg-yellow-400 text-stone-900 max-md:pl-5">
                        Subscribe
                      </div>
                    </div>
                    <div className="mt-4 text-xs leading-5 text-stone-50">
                      By subscribing, you agree to our Privacy Policy and
                      consent to receive updates from our company.
                    </div>
                  </div>
                </div>
              </div>
            </div>
          </div>
        </div>
        <div className="flex flex-col mt-9 max-md:max-w-full">
          <div className="shrink-0 h-px bg-white border border-white border-solid max-md:max-w-full" />
          <div className="flex gap-5 justify-between mt-8 w-full max-md:flex-wrap max-md:max-w-full">
            <div className="flex gap-5 justify-between self-start text-sm leading-5 max-md:flex-wrap">
              <div className="underline text-stone-50">
                © 2023 Bolster. All rights reserved.
              </div>
              <div className="flex gap-5 justify-between text-yellow-400">
                <div className="underline">Terms of Service</div>
                <div className="underline">Privacy Policy</div>
              </div>
            </div>
            <div className="flex gap-3">
              <img
                loading="lazy"
                src="https://cdn.builder.io/api/v1/image/assets/TEMP/8ec0c3725633a4b5e7770e52b9be50077e8a0c9e5023ca2df9601a12dd1db9d8?apiKey=3c43d1e5501c48e2896654e6368e313f&"
                className="shrink-0 w-6 aspect-square"
              />
              <img
                loading="lazy"
                src="https://cdn.builder.io/api/v1/image/assets/TEMP/3a13253f7de1114481cd9bb6306631115938a769a431a06de8956b1dcf857511?apiKey=3c43d1e5501c48e2896654e6368e313f&"
                className="shrink-0 w-6 aspect-square"
              />
              <img
                loading="lazy"
                src="https://cdn.builder.io/api/v1/image/assets/TEMP/40afb6c34a4a95c0d76310ac3ef976ddc7aa6eceb726183b62001976912963a5?apiKey=3c43d1e5501c48e2896654e6368e313f&"
                className="shrink-0 w-6 aspect-square"
              />
              <img
                loading="lazy"
                src="https://cdn.builder.io/api/v1/image/assets/TEMP/616539961eda8ea16abf265b3c6b28e66405318a3cf7c77a3c50a34d3623c32b?apiKey=3c43d1e5501c48e2896654e6368e313f&"
                className="shrink-0 w-6 aspect-square"
              />
              <img
                loading="lazy"
                src="https://cdn.builder.io/api/v1/image/assets/TEMP/dffe7183f8f51e12b6dc159ec22c3c11973860bf3d4f3112df33589efa46c6ea?apiKey=3c43d1e5501c48e2896654e6368e313f&"
                className="shrink-0 w-6 aspect-square"
              />
            </div>
          </div>
        </div>
      </div>
    </>
  );
}