/**
 * This code was generated by Builder.io.
 */
import * as React from "react";

function MyComponent() {
  return (
    <div className="flex flex-col p-10 mx-auto w-full bg-white rounded-xl border-2 border-solid shadow-sm border-stone-900 border-opacity-20 max-w-[967px] max-md:px-5 max-md:max-w-full max-sm:pt-8">
      <div className="flex flex-col justify-center text-black max-md:max-w-full">
        <div className="flex flex-col max-md:max-w-full">
          <div className="justify-center text-4xl font-bold leading-10 bg-white max-md:max-w-full max-sm:bg-white">
            <span className="bg-yellow-400">One-visit closes </span>
            <br />
          </div>
          <div className="mt-6 w-6/12 text-base leading-6 max-md:max-w-full max-sm:w-full">
            <span className="">
              Maximize your efficiency with quick and accurate estimating
              designed to speed up your sales cycle and eliminate the need for
              return visits.
            </span>
          </div>
        </div>
      </div>
      <div className="flex flex-col mt-8 max-md:max-w-full">
        <div className="max-md:max-w-full">
          <div className="flex gap-5 max-md:flex-col max-md:gap-0">
            <div className="flex flex-col w-6/12 max-md:ml-0 max-md:w-full">
              <div className="flex flex-col grow justify-center max-md:mt-8 max-md:max-w-full">
                <div className="flex flex-col justify-center px-8 py-14 rounded-xl bg-stone-200 max-md:max-w-full">
                  <img
                    loading="lazy"
                    srcSet="https://cdn.builder.io/api/v1/image/assets/TEMP/ab22abd4996a7804e559836d037ba0c525da0284301acdcf4cf036fafa9768a8?apiKey=3c43d1e5501c48e2896654e6368e313f&width=100 100w, https://cdn.builder.io/api/v1/image/assets/TEMP/ab22abd4996a7804e559836d037ba0c525da0284301acdcf4cf036fafa9768a8?apiKey=3c43d1e5501c48e2896654e6368e313f&width=200 200w, https://cdn.builder.io/api/v1/image/assets/TEMP/ab22abd4996a7804e559836d037ba0c525da0284301acdcf4cf036fafa9768a8?apiKey=3c43d1e5501c48e2896654e6368e313f&width=400 400w, https://cdn.builder.io/api/v1/image/assets/TEMP/ab22abd4996a7804e559836d037ba0c525da0284301acdcf4cf036fafa9768a8?apiKey=3c43d1e5501c48e2896654e6368e313f&width=800 800w, https://cdn.builder.io/api/v1/image/assets/TEMP/ab22abd4996a7804e559836d037ba0c525da0284301acdcf4cf036fafa9768a8?apiKey=3c43d1e5501c48e2896654e6368e313f&width=1200 1200w, https://cdn.builder.io/api/v1/image/assets/TEMP/ab22abd4996a7804e559836d037ba0c525da0284301acdcf4cf036fafa9768a8?apiKey=3c43d1e5501c48e2896654e6368e313f&width=1600 1600w, https://cdn.builder.io/api/v1/image/assets/TEMP/ab22abd4996a7804e559836d037ba0c525da0284301acdcf4cf036fafa9768a8?apiKey=3c43d1e5501c48e2896654e6368e313f&width=2000 2000w, https://cdn.builder.io/api/v1/image/assets/TEMP/ab22abd4996a7804e559836d037ba0c525da0284301acdcf4cf036fafa9768a8?apiKey=3c43d1e5501c48e2896654e6368e313f&"
                    className="w-full max-w-full aspect-[1.64]"
                  />
                </div>
              </div>
            </div>
            <div className="flex flex-col ml-5 w-6/12 max-md:ml-0 max-md:w-full">
              <div className="flex flex-col grow justify-center max-md:mt-8 max-md:max-w-full">
                <div className="flex flex-col justify-center px-8 py-14 rounded-xl bg-stone-200 max-md:max-w-full">
                  <img
                    loading="lazy"
                    srcSet="https://cdn.builder.io/api/v1/image/assets/TEMP/ab22abd4996a7804e559836d037ba0c525da0284301acdcf4cf036fafa9768a8?apiKey=3c43d1e5501c48e2896654e6368e313f&width=100 100w, https://cdn.builder.io/api/v1/image/assets/TEMP/ab22abd4996a7804e559836d037ba0c525da0284301acdcf4cf036fafa9768a8?apiKey=3c43d1e5501c48e2896654e6368e313f&width=200 200w, https://cdn.builder.io/api/v1/image/assets/TEMP/ab22abd4996a7804e559836d037ba0c525da0284301acdcf4cf036fafa9768a8?apiKey=3c43d1e5501c48e2896654e6368e313f&width=400 400w, https://cdn.builder.io/api/v1/image/assets/TEMP/ab22abd4996a7804e559836d037ba0c525da0284301acdcf4cf036fafa9768a8?apiKey=3c43d1e5501c48e2896654e6368e313f&width=800 800w, https://cdn.builder.io/api/v1/image/assets/TEMP/ab22abd4996a7804e559836d037ba0c525da0284301acdcf4cf036fafa9768a8?apiKey=3c43d1e5501c48e2896654e6368e313f&width=1200 1200w, https://cdn.builder.io/api/v1/image/assets/TEMP/ab22abd4996a7804e559836d037ba0c525da0284301acdcf4cf036fafa9768a8?apiKey=3c43d1e5501c48e2896654e6368e313f&width=1600 1600w, https://cdn.builder.io/api/v1/image/assets/TEMP/ab22abd4996a7804e559836d037ba0c525da0284301acdcf4cf036fafa9768a8?apiKey=3c43d1e5501c48e2896654e6368e313f&width=2000 2000w, https://cdn.builder.io/api/v1/image/assets/TEMP/ab22abd4996a7804e559836d037ba0c525da0284301acdcf4cf036fafa9768a8?apiKey=3c43d1e5501c48e2896654e6368e313f&"
                    className="w-full max-w-full aspect-[1.64]"
                  />
                </div>
              </div>
            </div>
          </div>
        </div>
        <div className="mt-8 text-base leading-6 text-black max-md:max-w-full">
          Whether you're crafting a bespoke deck, installing elegant fencing, or
          building an outdoor kitchen, our software offers unparalleled
          flexibility in quoting. Present detailed options and upgrades within
          your estimates, facilitating clear communication and enabling
          effective upselling. With our solution, you can achieve accurate
          estimates on the first call, catering to both large-scale designs and
          high-volume requests, ensuring your service stands out in a
          competitive market.
        </div>
        <div className="flex flex-col justify-center mt-8 max-w-full text-xl font-bold text-stone-900 w-[197px]">
          <div className="justify-center px-11 py-3 bg-yellow-400 max-md:px-5 max-sm:mr-auto">
            Learn More
          </div>
        </div>
      </div>
    </div>
  );
}