/**
 * This code was generated by Builder.io.
 */
import * as React from "react";

function MyComponent() {
  return (
    <>
      <div className="flex flex-col justify-center bg-white">
        <div className="flex flex-col w-full max-md:max-w-full">
          <div className="flex overflow-hidden relative flex-col justify-center pt-2.5 pb-20 w-full min-h-[832px] max-md:max-w-full">
            <img
              loading="lazy"
              srcSet="https://cdn.builder.io/api/v1/image/assets/TEMP/f8bfe548bc32d40ebde8f5b9523115c0514e7ce639c8ed1f58b21ad6adc931ee?apiKey=3c43d1e5501c48e2896654e6368e313f&width=100 100w, https://cdn.builder.io/api/v1/image/assets/TEMP/f8bfe548bc32d40ebde8f5b9523115c0514e7ce639c8ed1f58b21ad6adc931ee?apiKey=3c43d1e5501c48e2896654e6368e313f&width=200 200w, https://cdn.builder.io/api/v1/image/assets/TEMP/f8bfe548bc32d40ebde8f5b9523115c0514e7ce639c8ed1f58b21ad6adc931ee?apiKey=3c43d1e5501c48e2896654e6368e313f&width=400 400w, https://cdn.builder.io/api/v1/image/assets/TEMP/f8bfe548bc32d40ebde8f5b9523115c0514e7ce639c8ed1f58b21ad6adc931ee?apiKey=3c43d1e5501c48e2896654e6368e313f&width=800 800w, https://cdn.builder.io/api/v1/image/assets/TEMP/f8bfe548bc32d40ebde8f5b9523115c0514e7ce639c8ed1f58b21ad6adc931ee?apiKey=3c43d1e5501c48e2896654e6368e313f&width=1200 1200w, https://cdn.builder.io/api/v1/image/assets/TEMP/f8bfe548bc32d40ebde8f5b9523115c0514e7ce639c8ed1f58b21ad6adc931ee?apiKey=3c43d1e5501c48e2896654e6368e313f&width=1600 1600w, https://cdn.builder.io/api/v1/image/assets/TEMP/f8bfe548bc32d40ebde8f5b9523115c0514e7ce639c8ed1f58b21ad6adc931ee?apiKey=3c43d1e5501c48e2896654e6368e313f&width=2000 2000w, https://cdn.builder.io/api/v1/image/assets/TEMP/f8bfe548bc32d40ebde8f5b9523115c0514e7ce639c8ed1f58b21ad6adc931ee?apiKey=3c43d1e5501c48e2896654e6368e313f&"
              className="object-cover absolute inset-0 size-full"
            />
            <div className="flex relative flex-row gap-5 justify-between px-16 py-2 mb-auto w-full max-md:px-5 max-md:max-w-full">
              <img
                loading="lazy"
                src="https://cdn.builder.io/api/v1/image/assets/TEMP/a6f0226e7096b413711dfc55417603b99fdce9b0afb17ed90cdff827c740482f?apiKey=3c43d1e5501c48e2896654e6368e313f&"
                className="shrink-0 max-w-full aspect-[3.23] w-[180px]"
              />
              <div className="flex gap-5 justify-between my-auto">
                <div className="flex flex-col justify-center px-px text-xl font-bold text-white">
                  <div className="justify-center px-9 py-3 bg-blue-600 max-md:px-5">
                    Book a Demo
                  </div>
                </div>
                <div
                  className="flex flex-col justify-center py-1.5 my-auto w-[35px]"
                >
                  <div className="shrink-0 h-1 bg-white max-sm:bg-black" />
                  <div className="shrink-0 mt-2 h-1 bg-white max-sm:bg-black" />
                  <div className="shrink-0 mt-2 h-1 bg-white max-sm:bg-black" />
                </div>
              </div>
            </div>
            <div className="flex relative flex-col justify-center items-start self-center px-16 mt-6 mb-2.5 w-auto max-w-full font-bold max-md:pr-5 max-sm:pl-5">
              <div className="flex flex-col justify-end pt-20 w-auto max-w-full">
                <div className="justify-center mt-44 w-6/12 text-5xl leading-[60px] text-stone-900 max-md:mt-10 max-md:max-w-full max-md:text-4xl max-md:leading-[53px] max-sm:w-full">
                  <span className="bg-yellow-400">
                    Shape the Great Outdoors with Confidence
                  </span>
                </div>
                <div className="mt-4 w-6/12 text-lg leading-7 text-stone-50 max-md:max-w-full max-sm:w-full">
                  From the initial estimate to the final payment, provide a
                  seamless experience for clients seeking exceptional outdoor
                  spaces. Our versatile estimating tools cater to the diverse
                  needs of hardscape projects, whether you're crafting a fence
                  project or an elaborate outdoor kitchen. Elevate your business
                  with the precision and flexibility needed to outperform in the
                  competition.
                </div>
                <div className="flex flex-col justify-center mt-4 mr-auto w-auto max-w-full text-xl text-white">
                  <div className="justify-center px-10 py-3 border-2 border-solid bg-stone-900 border-stone-900 max-md:px-5">
                    Get Started
                  </div>
                </div>
              </div>
            </div>
          </div>
          <div className="flex justify-center items-center p-10 w-full text-base leading-6 text-center text-black max-md:px-5 max-md:max-w-full">
            <div className="flex gap-5 max-md:flex-wrap max-sm:mx-auto">
              <div className="justify-center px-2.5 py-1.5 whitespace-nowrap max-sm:mx-auto">
                Estimation
              </div>
              <div className="justify-center px-2.5 py-1.5 max-sm:mx-auto">
                Client Dashboard
              </div>
              <div className="justify-center px-2.5 py-1.5 whitespace-nowrap max-sm:mx-auto">
                Scheduling
              </div>
              <div className="justify-center px-2.5 py-1.5 max-sm:mx-auto">
                Invoicing & Payments
              </div>
            </div>
          </div>
          <div className="flex flex-col justify-center px-16 py-20 w-full bg-stone-200 max-md:px-5 max-md:max-w-full max-sm:py-8">
            <div className="flex flex-col justify-center p-10 mx-auto my-2.5 w-full bg-white rounded-xl max-w-[1350px] max-md:px-5 max-md:mr-2.5 max-md:max-w-full max-sm:py-8">
              <div className="flex flex-col justify-center max-md:max-w-full">
                <div className="flex flex-col max-md:max-w-full">
                  <div className="flex flex-col text-black max-md:max-w-full">
                    <div className="text-4xl font-bold leading-10 max-md:max-w-full">
                      Streamlined Estimating for Efficiency
                    </div>
                    <div className="mt-6 text-lg leading-7 max-md:max-w-full">
                      Maximize your efficiency with our estimating tool designed
                      to speed up the sales cycle and eliminate the need for
                      return visits.
                    </div>
                  </div>
                  <div className="mt-8 max-md:max-w-full">
                    <div className="flex gap-5 max-md:flex-col max-md:gap-0">
                      <div className="flex flex-col w-6/12 max-md:ml-0 max-md:w-full">
                        <div className="shrink-0 self-stretch mx-auto max-w-full rounded-xl bg-stone-50 h-[473px] w-[494px] max-md:mt-8 max-sm:h-[250px]" />
                      </div>
                      <div className="flex flex-col ml-5 w-6/12 max-md:ml-0 max-md:w-full">
                        <div className="shrink-0 self-stretch mx-auto max-w-full rounded-xl bg-stone-50 h-[473px] w-[494px] max-md:mt-8 max-sm:h-[250px]" />
                      </div>
                    </div>
                  </div>
                  <div className="justify-center mt-8 text-lg leading-7 text-black max-md:max-w-full">
                    Our estimating tool goes beyond standard practices to level
                    up the homeowner experience and  support your sales from
                    start to finish. It demystifies pricing for homeowners,
                    illustrating how each choice affects the overall cost,
                    thereby fostering trust and understanding.
                  </div>
                  <div className="justify-center self-start px-11 py-3 mt-8 text-xl font-bold bg-yellow-400 text-stone-900 max-md:px-5">
                    Learn More
                  </div>
                </div>
              </div>
            </div>
          </div>
          <div className="flex flex-col justify-center w-full bg-white max-md:max-w-full">
            <div className="w-full max-md:max-w-full">
              <div className="flex gap-5 max-md:flex-col max-md:gap-0">
                <div className="flex flex-col w-6/12 max-md:ml-0 max-md:w-full">
                  <img
                    loading="lazy"
                    srcSet="https://cdn.builder.io/api/v1/image/assets/TEMP/6f946fa42e937b3ae6945063a5da4f09b36a0ab38fb1ca6731cf6a910489a354?apiKey=3c43d1e5501c48e2896654e6368e313f&width=100 100w, https://cdn.builder.io/api/v1/image/assets/TEMP/6f946fa42e937b3ae6945063a5da4f09b36a0ab38fb1ca6731cf6a910489a354?apiKey=3c43d1e5501c48e2896654e6368e313f&width=200 200w, https://cdn.builder.io/api/v1/image/assets/TEMP/6f946fa42e937b3ae6945063a5da4f09b36a0ab38fb1ca6731cf6a910489a354?apiKey=3c43d1e5501c48e2896654e6368e313f&width=400 400w, https://cdn.builder.io/api/v1/image/assets/TEMP/6f946fa42e937b3ae6945063a5da4f09b36a0ab38fb1ca6731cf6a910489a354?apiKey=3c43d1e5501c48e2896654e6368e313f&width=800 800w, https://cdn.builder.io/api/v1/image/assets/TEMP/6f946fa42e937b3ae6945063a5da4f09b36a0ab38fb1ca6731cf6a910489a354?apiKey=3c43d1e5501c48e2896654e6368e313f&width=1200 1200w, https://cdn.builder.io/api/v1/image/assets/TEMP/6f946fa42e937b3ae6945063a5da4f09b36a0ab38fb1ca6731cf6a910489a354?apiKey=3c43d1e5501c48e2896654e6368e313f&width=1600 1600w, https://cdn.builder.io/api/v1/image/assets/TEMP/6f946fa42e937b3ae6945063a5da4f09b36a0ab38fb1ca6731cf6a910489a354?apiKey=3c43d1e5501c48e2896654e6368e313f&width=2000 2000w, https://cdn.builder.io/api/v1/image/assets/TEMP/6f946fa42e937b3ae6945063a5da4f09b36a0ab38fb1ca6731cf6a910489a354?apiKey=3c43d1e5501c48e2896654e6368e313f&"
                    className="grow self-stretch w-full aspect-[0.58] max-md:max-w-full"
                  />
                </div>
                <div className="flex flex-col ml-5 w-6/12 max-md:ml-0 max-md:w-full">
                  <div className="flex flex-col grow justify-center px-16 py-20 max-md:px-5 max-md:max-w-full max-sm:py-10">
                    <div className="flex flex-col mx-6 mt-2.5 max-md:mr-2.5 max-md:max-w-full">
                      <div className="text-5xl font-bold text-black leading-[60px] max-md:max-w-full max-md:text-4xl max-md:leading-[53px] max-sm:text-4xl">
                        Simplified Project Management with CRM Dashboard
                      </div>
                      <div className="mt-6 text-lg leading-7 text-black max-md:max-w-full">
                        Our CRM dashboard offers a straightforward way to
                        monitor project progress and customer engagement.
                      </div>
                      <div className="flex flex-col justify-center px-9 py-11 mt-8 rounded-xl bg-stone-200 max-md:px-5 max-sm:py-12">
                        <img
                          loading="lazy"
                          srcSet="https://cdn.builder.io/api/v1/image/assets/TEMP/ab22abd4996a7804e559836d037ba0c525da0284301acdcf4cf036fafa9768a8?apiKey=3c43d1e5501c48e2896654e6368e313f&width=100 100w, https://cdn.builder.io/api/v1/image/assets/TEMP/ab22abd4996a7804e559836d037ba0c525da0284301acdcf4cf036fafa9768a8?apiKey=3c43d1e5501c48e2896654e6368e313f&width=200 200w, https://cdn.builder.io/api/v1/image/assets/TEMP/ab22abd4996a7804e559836d037ba0c525da0284301acdcf4cf036fafa9768a8?apiKey=3c43d1e5501c48e2896654e6368e313f&width=400 400w, https://cdn.builder.io/api/v1/image/assets/TEMP/ab22abd4996a7804e559836d037ba0c525da0284301acdcf4cf036fafa9768a8?apiKey=3c43d1e5501c48e2896654e6368e313f&width=800 800w, https://cdn.builder.io/api/v1/image/assets/TEMP/ab22abd4996a7804e559836d037ba0c525da0284301acdcf4cf036fafa9768a8?apiKey=3c43d1e5501c48e2896654e6368e313f&width=1200 1200w, https://cdn.builder.io/api/v1/image/assets/TEMP/ab22abd4996a7804e559836d037ba0c525da0284301acdcf4cf036fafa9768a8?apiKey=3c43d1e5501c48e2896654e6368e313f&width=1600 1600w, https://cdn.builder.io/api/v1/image/assets/TEMP/ab22abd4996a7804e559836d037ba0c525da0284301acdcf4cf036fafa9768a8?apiKey=3c43d1e5501c48e2896654e6368e313f&width=2000 2000w, https://cdn.builder.io/api/v1/image/assets/TEMP/ab22abd4996a7804e559836d037ba0c525da0284301acdcf4cf036fafa9768a8?apiKey=3c43d1e5501c48e2896654e6368e313f&"
                          className="w-full max-w-full aspect-[1.64]"
                        />
                      </div>
                      <div className="flex flex-col justify-center mt-6 max-md:max-w-full">
                        <div className="flex flex-col max-md:max-w-full">
                          <div className="justify-center text-lg leading-7 text-black max-md:max-w-full">
                            Our estimating tool goes beyond standard practices
                            to level up the homeowner experience and  support
                            your sales from start to finish. It demystifies
                            pricing for homeowners, illustrating how each choice
                            affects the overall cost, thereby fostering trust
                            and understanding.
                          </div>
                          <div className="justify-center self-start px-11 py-3 mt-8 text-xl font-bold bg-yellow-400 text-stone-900 max-md:px-5">
                            Learn More
                          </div>
                        </div>
                      </div>
                    </div>
                  </div>
                </div>
              </div>
            </div>
          </div>
          <div className="flex flex-col justify-center px-16 py-20 w-full bg-yellow-400 max-md:px-5 max-md:max-w-full">
            <div className="flex flex-col py-10 mx-auto my-2.5 w-full rounded-xl max-w-[1350px] max-md:px-5 max-md:mr-2.5 max-md:max-w-full">
              <div className="flex flex-col justify-center px-16 text-black max-md:px-5 max-md:max-w-full">
                <div className="flex flex-col max-md:mr-2.5 max-md:max-w-full">
                  <div className="text-4xl font-bold leading-10 text-center max-md:max-w-full max-sm:text-left">
                    Efficient Scheduling to Optimize Resources
                  </div>
                  <div className="mt-6 text-lg leading-7 text-center max-md:max-w-full max-sm:text-left">
                    Organize your workforce and manage job allocations with our
                    advanced scheduling tool.
                  </div>
                </div>
              </div>
              <div className="mt-10 max-md:max-w-full">
                <div className="flex gap-5 max-md:flex-col max-md:gap-0">
                  <div className="flex flex-col w-6/12 max-md:ml-0 max-md:w-full">
                    <div className="shrink-0 rounded-xl bg-stone-50 h-[400px] max-md:max-w-full max-sm:h-[250px]" />
                  </div>
                  <div className="flex flex-col ml-5 w-6/12 max-md:ml-0 max-md:w-full">
                    <div className="flex flex-col grow justify-center max-md:mt-8 max-md:max-w-full">
                      <div className="flex flex-col justify-center max-md:max-w-full">
                        <div className="shrink-0 rounded-xl bg-stone-50 h-[400px] max-md:max-w-full max-sm:h-[250px]" />
                      </div>
                      <div className="flex flex-col justify-center max-md:max-w-full" />
                    </div>
                  </div>
                </div>
              </div>
              <div className="justify-center mt-8 text-base leading-6 text-black max-md:max-w-full">
                This bird's eye view of all you jobs helps allows you to book
                jobs on the spot based on availability in the schedule. Use this
                to create a sense of urgency in sales conversations to boost
                your closing rate.
              </div>
              <div className="justify-center self-start px-11 py-3 mt-8 text-xl font-bold text-white bg-black max-md:px-5">
                Learn More
              </div>
            </div>
          </div>
          <div className="flex flex-col justify-center px-16 py-20 w-full bg-stone-900 max-md:flex max-md:px-5 max-md:max-w-full max-sm:hidden max-sm:py-10">
            <div className="mx-8 my-2.5 max-md:mr-2.5 max-md:max-w-full">
              <div className="flex gap-5 max-md:flex-col max-md:gap-0">
                <div className="flex flex-col w-6/12 max-md:ml-0 max-md:w-full">
                  <img
                    loading="lazy"
                    srcSet="https://cdn.builder.io/api/v1/image/assets/TEMP/ed6dfcb1568b750e345ecb0ac4a4147f0be609c34ab7949ad50b740fe89d8693?apiKey=3c43d1e5501c48e2896654e6368e313f&width=100 100w, https://cdn.builder.io/api/v1/image/assets/TEMP/ed6dfcb1568b750e345ecb0ac4a4147f0be609c34ab7949ad50b740fe89d8693?apiKey=3c43d1e5501c48e2896654e6368e313f&width=200 200w, https://cdn.builder.io/api/v1/image/assets/TEMP/ed6dfcb1568b750e345ecb0ac4a4147f0be609c34ab7949ad50b740fe89d8693?apiKey=3c43d1e5501c48e2896654e6368e313f&width=400 400w, https://cdn.builder.io/api/v1/image/assets/TEMP/ed6dfcb1568b750e345ecb0ac4a4147f0be609c34ab7949ad50b740fe89d8693?apiKey=3c43d1e5501c48e2896654e6368e313f&width=800 800w, https://cdn.builder.io/api/v1/image/assets/TEMP/ed6dfcb1568b750e345ecb0ac4a4147f0be609c34ab7949ad50b740fe89d8693?apiKey=3c43d1e5501c48e2896654e6368e313f&width=1200 1200w, https://cdn.builder.io/api/v1/image/assets/TEMP/ed6dfcb1568b750e345ecb0ac4a4147f0be609c34ab7949ad50b740fe89d8693?apiKey=3c43d1e5501c48e2896654e6368e313f&width=1600 1600w, https://cdn.builder.io/api/v1/image/assets/TEMP/ed6dfcb1568b750e345ecb0ac4a4147f0be609c34ab7949ad50b740fe89d8693?apiKey=3c43d1e5501c48e2896654e6368e313f&width=2000 2000w, https://cdn.builder.io/api/v1/image/assets/TEMP/ed6dfcb1568b750e345ecb0ac4a4147f0be609c34ab7949ad50b740fe89d8693?apiKey=3c43d1e5501c48e2896654e6368e313f&"
                    className="object-cover grow w-full border border-black border-solid aspect-[0.85] max-md:max-w-full max-sm:h-[150px]"
                  />
                </div>
                <div className="flex flex-col ml-5 w-6/12 max-md:ml-0 max-md:w-full">
                  <img
                    loading="lazy"
                    srcSet="https://cdn.builder.io/api/v1/image/assets/TEMP/5ff1cd55db1a46657c55594830f346a547c6ab51e97368972d2ab5bae95cd8c8?apiKey=3c43d1e5501c48e2896654e6368e313f&width=100 100w, https://cdn.builder.io/api/v1/image/assets/TEMP/5ff1cd55db1a46657c55594830f346a547c6ab51e97368972d2ab5bae95cd8c8?apiKey=3c43d1e5501c48e2896654e6368e313f&width=200 200w, https://cdn.builder.io/api/v1/image/assets/TEMP/5ff1cd55db1a46657c55594830f346a547c6ab51e97368972d2ab5bae95cd8c8?apiKey=3c43d1e5501c48e2896654e6368e313f&width=400 400w, https://cdn.builder.io/api/v1/image/assets/TEMP/5ff1cd55db1a46657c55594830f346a547c6ab51e97368972d2ab5bae95cd8c8?apiKey=3c43d1e5501c48e2896654e6368e313f&width=800 800w, https://cdn.builder.io/api/v1/image/assets/TEMP/5ff1cd55db1a46657c55594830f346a547c6ab51e97368972d2ab5bae95cd8c8?apiKey=3c43d1e5501c48e2896654e6368e313f&width=1200 1200w, https://cdn.builder.io/api/v1/image/assets/TEMP/5ff1cd55db1a46657c55594830f346a547c6ab51e97368972d2ab5bae95cd8c8?apiKey=3c43d1e5501c48e2896654e6368e313f&width=1600 1600w, https://cdn.builder.io/api/v1/image/assets/TEMP/5ff1cd55db1a46657c55594830f346a547c6ab51e97368972d2ab5bae95cd8c8?apiKey=3c43d1e5501c48e2896654e6368e313f&width=2000 2000w, https://cdn.builder.io/api/v1/image/assets/TEMP/5ff1cd55db1a46657c55594830f346a547c6ab51e97368972d2ab5bae95cd8c8?apiKey=3c43d1e5501c48e2896654e6368e313f&"
                    className="grow self-stretch w-full aspect-[0.87] max-md:max-w-full"
                  />
                </div>
              </div>
            </div>
          </div>
          <div className="hidden flex-col justify-center p-5 bg-stone-900 max-w-[375px] max-md:hidden max-sm:flex">
            <div className="flex flex-col">
              <img
                loading="lazy"
                srcSet="https://cdn.builder.io/api/v1/image/assets/TEMP/06776d89ceab9204235c240858371968b6c339c8e91b205dc3f8c9f26fd62688?apiKey=3c43d1e5501c48e2896654e6368e313f&width=100 100w, https://cdn.builder.io/api/v1/image/assets/TEMP/06776d89ceab9204235c240858371968b6c339c8e91b205dc3f8c9f26fd62688?apiKey=3c43d1e5501c48e2896654e6368e313f&width=200 200w, https://cdn.builder.io/api/v1/image/assets/TEMP/06776d89ceab9204235c240858371968b6c339c8e91b205dc3f8c9f26fd62688?apiKey=3c43d1e5501c48e2896654e6368e313f&width=400 400w, https://cdn.builder.io/api/v1/image/assets/TEMP/06776d89ceab9204235c240858371968b6c339c8e91b205dc3f8c9f26fd62688?apiKey=3c43d1e5501c48e2896654e6368e313f&width=800 800w, https://cdn.builder.io/api/v1/image/assets/TEMP/06776d89ceab9204235c240858371968b6c339c8e91b205dc3f8c9f26fd62688?apiKey=3c43d1e5501c48e2896654e6368e313f&width=1200 1200w, https://cdn.builder.io/api/v1/image/assets/TEMP/06776d89ceab9204235c240858371968b6c339c8e91b205dc3f8c9f26fd62688?apiKey=3c43d1e5501c48e2896654e6368e313f&width=1600 1600w, https://cdn.builder.io/api/v1/image/assets/TEMP/06776d89ceab9204235c240858371968b6c339c8e91b205dc3f8c9f26fd62688?apiKey=3c43d1e5501c48e2896654e6368e313f&width=2000 2000w, https://cdn.builder.io/api/v1/image/assets/TEMP/06776d89ceab9204235c240858371968b6c339c8e91b205dc3f8c9f26fd62688?apiKey=3c43d1e5501c48e2896654e6368e313f&"
                className="w-full border border-black border-solid aspect-[1.75]"
              />
              <img
                loading="lazy"
                srcSet="https://cdn.builder.io/api/v1/image/assets/TEMP/b7af71e477494bdb32bdfaa1ad04dd01155305af1c315fdd0257f7c8106a26dc?apiKey=3c43d1e5501c48e2896654e6368e313f&width=100 100w, https://cdn.builder.io/api/v1/image/assets/TEMP/b7af71e477494bdb32bdfaa1ad04dd01155305af1c315fdd0257f7c8106a26dc?apiKey=3c43d1e5501c48e2896654e6368e313f&width=200 200w, https://cdn.builder.io/api/v1/image/assets/TEMP/b7af71e477494bdb32bdfaa1ad04dd01155305af1c315fdd0257f7c8106a26dc?apiKey=3c43d1e5501c48e2896654e6368e313f&width=400 400w, https://cdn.builder.io/api/v1/image/assets/TEMP/b7af71e477494bdb32bdfaa1ad04dd01155305af1c315fdd0257f7c8106a26dc?apiKey=3c43d1e5501c48e2896654e6368e313f&width=800 800w, https://cdn.builder.io/api/v1/image/assets/TEMP/b7af71e477494bdb32bdfaa1ad04dd01155305af1c315fdd0257f7c8106a26dc?apiKey=3c43d1e5501c48e2896654e6368e313f&width=1200 1200w, https://cdn.builder.io/api/v1/image/assets/TEMP/b7af71e477494bdb32bdfaa1ad04dd01155305af1c315fdd0257f7c8106a26dc?apiKey=3c43d1e5501c48e2896654e6368e313f&width=1600 1600w, https://cdn.builder.io/api/v1/image/assets/TEMP/b7af71e477494bdb32bdfaa1ad04dd01155305af1c315fdd0257f7c8106a26dc?apiKey=3c43d1e5501c48e2896654e6368e313f&width=2000 2000w, https://cdn.builder.io/api/v1/image/assets/TEMP/b7af71e477494bdb32bdfaa1ad04dd01155305af1c315fdd0257f7c8106a26dc?apiKey=3c43d1e5501c48e2896654e6368e313f&"
                className="w-full aspect-[1.75]"
              />
            </div>
          </div>
          <div className="flex flex-col justify-center px-16 py-20 w-full bg-stone-50 max-md:px-5 max-md:max-w-full max-sm:pt-10">
            <div className="flex flex-col p-10 mx-auto my-2.5 w-full bg-white rounded-xl border-2 border-solid shadow-sm border-stone-900 border-opacity-20 max-w-[1350px] max-md:px-5 max-md:mr-2.5 max-md:max-w-full max-sm:pt-8">
              <div className="flex flex-col justify-center max-w-full text-black w-[631px]">
                <div className="flex flex-col justify-center max-md:max-w-full">
                  <div className="flex flex-col max-md:max-w-full">
                    <div className="text-4xl font-bold leading-10 max-md:max-w-full">
                      Quick Invoicing & Payments for Better Cash Flow
                    </div>
                    <div className="mt-6 text-lg leading-7 max-md:max-w-full">
                      Ease your administrative load with our quick invoicing and
                      integrated payments system.
                    </div>
                  </div>
                </div>
              </div>
              <div className="mt-8 max-md:max-w-full">
                <div className="flex gap-5 max-md:flex-col max-md:gap-0">
                  <div className="flex flex-col w-6/12 max-md:ml-0 max-md:w-full">
                    <div className="flex flex-col grow max-md:mt-8 max-md:max-w-full">
                      <div className="flex flex-col justify-center bg-yellow-400 rounded-xl max-md:max-w-full max-sm:rounded-xl">
                        <div className="flex flex-col justify-center rounded-xl max-md:max-w-full max-sm:rounded-xl">
                          <img
                            loading="lazy"
                            srcSet="https://cdn.builder.io/api/v1/image/assets/TEMP/2790cffa27f3b6668c9cdf69e61160af1b1c0e6ea7e4364bd1eaa29b426608c1?apiKey=3c43d1e5501c48e2896654e6368e313f&width=100 100w, https://cdn.builder.io/api/v1/image/assets/TEMP/2790cffa27f3b6668c9cdf69e61160af1b1c0e6ea7e4364bd1eaa29b426608c1?apiKey=3c43d1e5501c48e2896654e6368e313f&width=200 200w, https://cdn.builder.io/api/v1/image/assets/TEMP/2790cffa27f3b6668c9cdf69e61160af1b1c0e6ea7e4364bd1eaa29b426608c1?apiKey=3c43d1e5501c48e2896654e6368e313f&width=400 400w, https://cdn.builder.io/api/v1/image/assets/TEMP/2790cffa27f3b6668c9cdf69e61160af1b1c0e6ea7e4364bd1eaa29b426608c1?apiKey=3c43d1e5501c48e2896654e6368e313f&width=800 800w, https://cdn.builder.io/api/v1/image/assets/TEMP/2790cffa27f3b6668c9cdf69e61160af1b1c0e6ea7e4364bd1eaa29b426608c1?apiKey=3c43d1e5501c48e2896654e6368e313f&width=1200 1200w, https://cdn.builder.io/api/v1/image/assets/TEMP/2790cffa27f3b6668c9cdf69e61160af1b1c0e6ea7e4364bd1eaa29b426608c1?apiKey=3c43d1e5501c48e2896654e6368e313f&width=1600 1600w, https://cdn.builder.io/api/v1/image/assets/TEMP/2790cffa27f3b6668c9cdf69e61160af1b1c0e6ea7e4364bd1eaa29b426608c1?apiKey=3c43d1e5501c48e2896654e6368e313f&width=2000 2000w, https://cdn.builder.io/api/v1/image/assets/TEMP/2790cffa27f3b6668c9cdf69e61160af1b1c0e6ea7e4364bd1eaa29b426608c1?apiKey=3c43d1e5501c48e2896654e6368e313f&"
                            className="w-full aspect-square max-md:max-w-full max-sm:rounded-xl"
                          />
                        </div>
                      </div>
                      <div className="flex flex-col mt-8 max-md:max-w-full">
                        <div className="text-base leading-6 text-black max-md:max-w-full">
                          Issue invoices with a click and enjoy the convenience
                          of online payments, facilitating faster settlements
                          and reduced administrative hassles. Our integrated
                          approach ensures nothing gets missed, from project
                          start to payment completion, with capped fees and
                          options for quicker access to your earnings.
                          Streamline your financial operations to focus more on
                          what you do best.
                        </div>
                        <div className="justify-center self-start px-11 py-3 mt-6 text-xl font-bold bg-yellow-400 text-stone-900 max-md:px-5">
                          Learn More
                        </div>
                      </div>
                    </div>
                  </div>
                  <div className="flex flex-col ml-5 w-6/12 max-md:ml-0 max-md:w-full">
                    <div className="flex flex-col grow self-stretch my-auto max-md:mt-8 max-md:max-w-full">
                      <div className="shrink-0 rounded-xl bg-stone-200 h-[47%] max-md:max-w-full max-sm:h-[250px]" />
                      <div className="shrink-0 mt-12 rounded-xl bg-stone-200 h-[47%] max-md:max-w-full max-sm:h-[250px]" />
                    </div>
                  </div>
                </div>
              </div>
            </div>
          </div>
        </div>
      </div>
      <div className="flex flex-row bg-white max-sm:flex max-sm:flex-col max-sm:bg-yellow-400">
        <div className="grow justify-center items-start px-16 py-20 w-auto text-8xl font-bold tracking-tighter bg-yellow-400 leading-[91px] text-stone-900 max-md:pt-10 max-md:pr-5 max-md:pl-6 max-md:max-w-full max-md:text-4xl max-md:leading-10 max-sm:w-4/5">
          Your essential tool for success
        </div>
        <div className="flex flex-col flex-wrap content-center p-16 my-24 mr-16 ml-0 w-auto max-w-full text-xl leading-5 bg-stone-900 text-zinc-500 max-md:px-5 max-md:mt-10 max-md:max-w-full max-sm:mx-5 max-sm:mt-5 max-sm:mb-8">
          <div className="text-5xl font-bold tracking-tighter text-white max-md:max-w-full max-md:text-4xl">
            Book a demo
          </div>
          <div className="mt-5 text-3xl tracking-tighter leading-7 text-white max-md:max-w-full">
            Let us show you how to boost efficiency and profitability on every
            project — from the foundation up.
          </div>
          <div className="flex gap-4 mt-5 tracking-tight max-md:flex-wrap max-sm:flex max-sm:flex-col">
            <div className="grow justify-center px-5 py-2.5 bg-white border border-solid border-neutral-600 w-fit max-sm:w-full">
              Full name
            </div>
            <div className="grow justify-center px-5 py-2.5 bg-white border border-solid border-neutral-600 w-fit max-sm:w-full">
              Demo date
            </div>
          </div>
          <div className="flex gap-4 mt-5 tracking-tight max-md:flex-wrap max-sm:flex max-sm:flex-col">
            <div className="grow justify-center px-5 py-2.5 bg-white border border-solid border-neutral-600 w-fit max-sm:w-full">
              Email address
            </div>
            <div className="grow justify-center px-5 py-2.5 bg-white border border-solid border-neutral-600 w-fit max-sm:w-full">
              Demo time
            </div>
          </div>
          <div className="flex gap-4 mt-5 tracking-tight max-md:flex-wrap max-sm:flex max-sm:flex-col">
            <div className="grow justify-center px-5 py-2.5 whitespace-nowrap bg-white border border-solid border-neutral-600 w-fit max-sm:w-full">
              Company
            </div>
            <div className="grow justify-center px-5 py-2.5 bg-white border border-solid border-neutral-600 w-fit max-sm:w-full">
              Any other information
            </div>
          </div>
          <div className="justify-center self-start px-14 py-5 mt-5 text-xl font-medium text-center whitespace-nowrap bg-yellow-400 text-stone-900 max-md:px-5 max-sm:w-6/12">
            Next
          </div>
        </div>
      </div>
      <div className="flex flex-col px-16 py-20 w-full bg-stone-900 max-md:px-5 max-md:max-w-full max-sm:pt-5 max-sm:pb-8">
        <div className="flex flex-col justify-center max-md:max-w-full">
          <div className="justify-between max-md:max-w-full">
            <div className="flex gap-5 max-md:flex-col max-md:gap-0">
              <div className="flex flex-col w-[61%] max-md:ml-0 max-md:w-full">
                <div className="grow self-stretch max-md:mt-10 max-md:max-w-full">
                  <div className="flex gap-5 max-md:flex-col max-md:gap-0">
                    <div className="flex flex-col w-[41%] max-md:ml-0 max-md:w-full">
                      <div className="flex flex-col grow justify-between self-stretch pr-3 text-base font-bold leading-6 text-center max-md:mt-10">
                        <img
                          loading="lazy"
                          src="https://cdn.builder.io/api/v1/image/assets/TEMP/10d16e7b0312cba51f479b22b65dcb82bb95362d2803659cefc44b8bab630bc0?apiKey=3c43d1e5501c48e2896654e6368e313f&"
                          className="self-stretch aspect-[3.23] w-[155px] max-sm:self-stretch"
                        />
                        <div className="flex flex-col justify-center mt-36 max-md:mt-10 max-sm:flex max-sm:flex-row">
                          <div className="justify-center px-2.5 py-1.5 bg-blue-600 text-stone-50 max-sm:mr-auto max-sm:w-2/5">
                            Book a demo
                          </div>
                          <div className="justify-center px-2.5 py-1.5 mt-2.5 whitespace-nowrap bg-stone-50 text-stone-900 max-md:px-5 max-sm:mr-auto max-sm:w-2/5">
                            Login
                          </div>
                        </div>
                      </div>
                    </div>
                    <div className="flex flex-col ml-5 w-[33%] max-md:ml-0 max-md:w-full">
                      <div className="flex flex-col leading-[150%] max-md:mt-10">
                        <div className="text-base font-bold text-yellow-400">
                          Resources
                        </div>
                        <div className="flex flex-col pb-9 mt-4 text-sm text-stone-50">
                          <div className="justify-center py-2">
                            Customer Success
                          </div>
                          <div className="justify-center py-2 whitespace-nowrap">
                            Blog
                          </div>
                          <div className="justify-center py-2 whitespace-nowrap">
                            University
                          </div>
                          <div className="justify-center py-2 whitespace-nowrap">
                            FAQ
                          </div>
                        </div>
                      </div>
                    </div>
                    <div className="flex flex-col ml-5 w-3/12 max-md:ml-0 max-md:w-full">
                      <div className="flex flex-col leading-[150%] max-md:mt-10">
                        <div className="text-base font-bold text-yellow-400">
                          Company
                        </div>
                        <div className="flex flex-col pb-9 mt-4 text-sm text-stone-50">
                          <div className="justify-center py-2">Our Story</div>
                          <div className="justify-center py-2 whitespace-nowrap">
                            Careers
                          </div>
                          <div className="justify-center py-2 whitespace-nowrap">
                            News
                          </div>
                          <div className="justify-center py-2">Contact Us</div>
                        </div>
                      </div>
                    </div>
                  </div>
                </div>
              </div>
              <div className="flex flex-col ml-5 w-[39%] max-md:ml-0 max-md:w-full">
                <div className="flex flex-col grow max-md:mt-10">
                  <div className="flex flex-col text-base">
                    <div className="font-bold text-yellow-400 leading-[150%]">
                      Subscribe
                    </div>
                    <div className="mt-4 leading-6 text-stone-50">
                      Stay informed with the latest news and updates.
                    </div>
                  </div>
                  <div className="flex flex-col mt-6">
                    <div className="flex flex-col text-base leading-6">
                      <div className="justify-center p-3 bg-white text-stone-500">
                        Enter your email
                      </div>
                      <div className="justify-center self-start px-5 py-3 mt-2 font-bold whitespace-nowrap bg-yellow-400 text-stone-900 max-md:pl-5">
                        Subscribe
                      </div>
                    </div>
                    <div className="mt-4 text-xs leading-5 text-stone-50">
                      By subscribing, you agree to our Privacy Policy and
                      consent to receive updates from our company.
                    </div>
                  </div>
                </div>
              </div>
            </div>
          </div>
        </div>
        <div className="flex flex-col mt-9 max-md:max-w-full">
          <div className="shrink-0 h-px bg-white border border-white border-solid max-md:max-w-full" />
          <div className="flex gap-5 justify-between mt-8 w-full max-md:flex-wrap max-md:max-w-full">
            <div className="flex gap-5 justify-between self-start text-sm leading-5 max-md:flex-wrap">
              <div className="underline text-stone-50">
                © 2023 Bolster. All rights reserved.
              </div>
              <div className="flex gap-5 justify-between text-yellow-400">
                <div className="underline">Terms of Service</div>
                <div className="underline">Privacy Policy</div>
              </div>
            </div>
            <div className="flex gap-3">
              <img
                loading="lazy"
                src="https://cdn.builder.io/api/v1/image/assets/TEMP/8ec0c3725633a4b5e7770e52b9be50077e8a0c9e5023ca2df9601a12dd1db9d8?apiKey=3c43d1e5501c48e2896654e6368e313f&"
                className="shrink-0 w-6 aspect-square"
              />
              <img
                loading="lazy"
                src="https://cdn.builder.io/api/v1/image/assets/TEMP/3a13253f7de1114481cd9bb6306631115938a769a431a06de8956b1dcf857511?apiKey=3c43d1e5501c48e2896654e6368e313f&"
                className="shrink-0 w-6 aspect-square"
              />
              <img
                loading="lazy"
                src="https://cdn.builder.io/api/v1/image/assets/TEMP/40afb6c34a4a95c0d76310ac3ef976ddc7aa6eceb726183b62001976912963a5?apiKey=3c43d1e5501c48e2896654e6368e313f&"
                className="shrink-0 w-6 aspect-square"
              />
              <img
                loading="lazy"
                src="https://cdn.builder.io/api/v1/image/assets/TEMP/616539961eda8ea16abf265b3c6b28e66405318a3cf7c77a3c50a34d3623c32b?apiKey=3c43d1e5501c48e2896654e6368e313f&"
                className="shrink-0 w-6 aspect-square"
              />
              <img
                loading="lazy"
                src="https://cdn.builder.io/api/v1/image/assets/TEMP/dffe7183f8f51e12b6dc159ec22c3c11973860bf3d4f3112df33589efa46c6ea?apiKey=3c43d1e5501c48e2896654e6368e313f&"
                className="shrink-0 w-6 aspect-square"
              />
            </div>
          </div>
        </div>
      </div>
    </>
  );
}